### ISSUE TITLE
MemoryError raised by circus-multi

### ISSUE THREAD

**Issue by balefebvre** [spyking-circus/spyking-circus#115]
Here is the traceback:

```
>> circus-multi <filename>.raw -e <extension>
Traceback (most recent call last):
  File "<...>\circus-multi-script.py", line 11, in <module>
    load_entry_point('spyking-circus==0.7.0', 'console_scripts', 'circus-multi')()
  File "<..>\lib\site-packages\circus\scripts\circus_multi.py", line 61, in main
    sub_results = slice_result(result, times)
  File "<...>\lib\site-packages\circus\shared\algorithms.py", line 334, in slice_result
    sub_result['spiketimes'][key] = result['spiketimes'][key][idx] - t[0]
MemoryError
```

**Comment by balefebvre** [comment]
Fixed with #116 .
