### ISSUE TITLE
problem with numpy.argpartition

### ISSUE THREAD

**Issue by yagui** [spyking-circus/spyking-circus#121]
Hello,

I'm using the latest version in the master branch (cloning the repo and then pip install spyking-circus ) and I'm having problems with this commit 
https://github.com/spyking-circus/spyking-circus/commit/b58482bd022d09b06360f5cf02fe8852fb8acb2b

If I revert this commit it works ok

I'm using this dataset
 https://github.com/kwikteam/phy-data/blob/master/template/sim_binary.dat

The program fails to run so I added 
print(data,nb_selec)  
at line 120 in algorithms.py and the output of the last 2 iterations is this

[16.976553  11.942155  13.899052  19.992535  19.46213   16.064741
  7.0859523  8.231348  17.427572  13.816171   7.5179853 14.285518
  8.2146635 16.881212  30.23115   33.54045   28.588667  20.393188
 16.721674   2.7818184 15.612877  15.327525  15.478889  15.201486
 15.680163  12.703392 ] 5
[23.414412 19.344591 15.933496 23.62514  23.922388] 5
Traceback (most recent call last):
  File "/home/ariel/virtualenvs/spyking2/.spk-test/bin/spyking-circus-subtask", line 11, in <module>
    load_entry_point('spyking-circus', 'console_scripts', 'spyking-circus-subtask')()
  File "/home/ariel/virtualenvs/spyking2/spyking-circus/build/lib/circus/scripts/subtask.py", line 43, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "/home/ariel/virtualenvs/spyking2/spyking-circus/build/lib/circus/__init__.py", line 21, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "/home/ariel/virtualenvs/spyking2/spyking-circus/build/lib/circus/clustering.py", line 640, in main
    rho, dist, sdist = algo.compute_rho(result['sub_%s_' %p + str(ielec)], mratio=m_ratio)
  File "/home/ariel/virtualenvs/spyking2/spyking-circus/build/lib/circus/shared/algorithms.py", line 122, in compute_rho
    dist_sorted[i] = data[numpy.argpartition(data, nb_selec)[:nb_selec]]  #numpy.sort(dist.get_row(i, with_diag=False))[:nb_selec]
  File "/home/ariel/virtualenvs/spyking2/.spk-test/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 808, in argpartition
    return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
  File "/home/ariel/virtualenvs/spyking2/.spk-test/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: kth(=5) out of bounds (5)
-------------------------------------------------------

**Comment by yagui** [comment]
I only needed to revert the line 120, the change in line 127 works without error.

**Comment by yger** [comment]
Thanks for spotting this bug, I'll fix it asap



Le mar. 4 juin 2019 à 18:36, Ariel Burman <notifications@github.com> a
écrit :

**Comment by yger** [comment]
Should be fixed in the latest commit. Let me know if you still have issues

**Comment by yagui** [comment]
yes, working great now! Thanks for the quick reply!
