### ISSUE TITLE
Issue on converting after last update (.8)

### ISSUE THREAD

**Issue by maurotoro** [spyking-circus/spyking-circus#125]
Dearest,

I've just updated to the last version to try the new phy interface, but when trying the converting step I get this error:
'    Traceback (most recent call last):
      File "/personal/scriptkid/virtenvs/spkcrc/bin/spyking-circus-subtask", line 10, in <module>
        sys.exit(main())
      File "/personal/scriptkid/virtenvs/spkcrc/lib/python3.7/site-packages/circus/scripts/subtask.py", line 41, in main
        circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu, extension=extension)
      File "/personal/scriptkid/virtenvs/spkcrc/lib/python3.7/site-packages/circus/__init__.py", line 19, in launch
        module.main(params, nb_cpu, nb_gpu, use_gpu, extension)
      File "/personal/scriptkid/virtenvs/spkcrc/lib/python3.7/site-packages/circus/converting.py", line 284, in main
        N_tm = write_templates(output_path, params, extension)
      File "/personal/scriptkid/virtenvs/spkcrc/lib/python3.7/site-packages/circus/converting.py", line 133, in write_templates
        waveform = io.get_stas(params, times_i=spikes, mean_mode=True, neighs=[elec], src=elec, labels_i=np.ones(len(spikes)))
      File "/personal/scriptkid/virtenvs/spkcrc/lib/python3.7/site-packages/circus/shared/files.py", line 112, in get_stas
        local_chunk = numpy.dot(local_chunk, spatial_whitening)
    ValueError: shapes (121,32) and (29,29) not aligned: 32 (dim 1) != 29 (dim 0)
`
Some more info, my recordings are from 32 electrodes in a silicone probe, but 3 channels are dead and non present on the .prb.

Any idea what could be happening?

**Comment by maurotoro** [comment]
This error seems to happen because I was ussing a param file for the previous version, after using the current example it did work. 

My bad...
