### ISSUE TITLE
Error in parsing Blackrock data (.ns6 file)

### ISSUE THREAD

**Issue by hangletn** [spyking-circus/spyking-circus#129]
Hello, I tried to use spyking circus for a Blackrock file (.ns6), and get the following error message:

`Traceback (most recent call last):
  File "C:\Users\Undergraduates\Anaconda3\Scripts\spyking-circus-script.py", line 11, in <module>
    load_entry_point('spyking-circus==0.8.0', 'console_scripts', 'spyking-circus')()
  File "C:\Users\Undergraduates\Anaconda3\lib\site-packages\circus\scripts\launch.py", line 215, in main
    data_file    = params.get_data_file(source=True, has_been_created=False)
  File "C:\Users\Undergraduates\Anaconda3\lib\site-packages\circus\shared\parser.py", line 563, in get_data_file
    return self._create_data_file(data_file, is_empty, params, stream_mode)
  File "C:\Users\Undergraduates\Anaconda3\lib\site-packages\circus\shared\parser.py", line 492, in _create_data_file
    data              = __supported_data_files__[file_format](data_file, params, is_empty, stream_mode)
  File "C:\Users\Undergraduates\Anaconda3\lib\site-packages\circus\files\datafile.py", line 132, in __init__
    self._fill_from_header(self._read_from_header())
  File "C:\Users\Undergraduates\Anaconda3\lib\site-packages\circus\files\blackrock.py", line 22, in _read_from_header
    self.size   = self.data.getdata('all', 0, 1/header['sampling_rate'])['data_headers'][0]['NumDataPoints']
  File "C:\Users\Undergraduates\Anaconda3\lib\site-packages\circus\files\utils\brpylib.py", line 898, in getdata
    timestamp    = unpack('<I', self.datafile.read(4))[0]
struct.error: unpack requires a buffer of 4 bytes` 

My recording file is 22GB, with 115 channels and about 60 minutes duration. I'm using Windows 10, Anaconda version 4.6.14, Python version 3.6.8, RAM 32GB.

I guess it's some problems with the parser of Blackrock file but not sure how to handle it. Any help will really be appreciated!

**Comment by yger** [comment]
Indeed, looks like there is an issue with the .ns6 file wrapper. Sorry for
that, but since we are not using this file format ourself, these errors are
hard to track. Could you share a small recording saved as .ns6, such that
we see how to load it? To avoid such errors, in the future:
- we plan to switch to neo.io, such that we hope file wrappers will be more
updated and keep better track of changes from manufacturers
- you could try to export the data as raw binary (should be an option with
your BlackRock software)

Best

Pierre

**Comment by hangletn** [comment]
Thank you, I've converted the file to binary and it works now.
