### ISSUE TITLE
Launcher Issue

### ISSUE THREAD

**Issue by Marrekko** [spyking-circus/spyking-circus#133]
Dear Pierre and Marcel,

I just installed the newest SpyKing and all required packages and visual 2015 on my windows 10 machine using Anaconda 3.7. Installation worked fine, however, I'm not able to launch Spyking in any way.

Starting up the GUI-Launcher will result in nothing (not even an error message). 

Launching the algorithm manually, resulted in this message at first:
````
C:\WINDOWS\system32>spyking-circus G:\SpykingData\Exp1_22_1\1dpost4APrem\35240N-1dpost-.h5
Traceback (most recent call last):
  File "C:\Users\Marek\Anaconda3\Scripts\spyking-circus-script.py", line 11, in <module>
    load_entry_point('spyking-circus==0.8.3', 'console_scripts', 'spyking-circus')()
  
File "C:\Users\Marek\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point return get_distribution(dist).load_entry_point(group, name)
  
File "C:\Users\Marek\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2843, in load_entry_point
    return ep.load()
  
File "C:\Users\Marek\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2434, in load
    return self.resolve()
  
File "C:\Users\Marek\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  
File "c:\users\marek\anaconda3\lib\site-packages\spyking_circus-0.8.3-py3.6.egg\circus\scripts\launch.py", line 157
    print Fore.RED + 'The parameter file %s is not present!' %file_params
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(Fore.RED + 'The parameter file %s is not present!' %file_params)?
````

So SpyKing did not even come to ask me whether I want to create a new template parameter file.
I checked code and changed in the suggested way.

Next Error:
```
`C:\WINDOWS\system32>spyking-circus G:\SpykingData\Exp1_22_1\1dpost4APrem\35240N-1dpost-.h5
Traceback (most recent call last):
  File "C:\Users\Marek\Anaconda3\Scripts\spyking-circus-script.py", line 11, in <module>
    load_entry_point('spyking-circus==0.8.3', 'console_scripts', 'spyking-circus')()
  File "C:\Users\Marek\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\Marek\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "C:\Users\Marek\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2434, in load
    return self.resolve()
  File "C:\Users\Marek\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\marek\anaconda3\lib\site-packages\spyking_circus-0.8.3-py3.6.egg\circus\scripts\launch.py", line 161
    print Fore.WHITE + "Creating", file_params
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(Fore.WHITE + "Creating", file_params)?
````

Afterwards:
````
C:\WINDOWS\system32>spyking-circus G:\SpykingData\Exp1_22_1\1dpost4APrem\35240N-1dpost-.h5
Traceback (most recent call last):
  File "C:\Users\Marek\Anaconda3\Scripts\spyking-circus-script.py", line 11, in <module>
    load_entry_point('spyking-circus==0.8.3', 'console_scripts', 'spyking-circus')()
  File "C:\Users\Marek\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\Marek\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "C:\Users\Marek\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2434, in load
    return self.resolve()
  File "C:\Users\Marek\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\marek\anaconda3\lib\site-packages\spyking_circus-0.8.3-py3.6.egg\circus\scripts\launch.py", line 292
    print get_colored_header()
                           ^
SyntaxError: invalid syntax
````

As I'm not into python scripting I dont know how to express a valid syntax of your code in line 292 and the followings. 

Can you help me debug? :)

Best regards

Marek

**Comment by yger** [comment]
How did you install Spyking circus exactly? With the conda command, or from
the git repo? Since you are using 0.8.3, I would assume that you used git,
am I right?

In fact, your errors indicate that you are running a python2 code with
python 3. So it may have been locally compiled with the wrong python

Pierre

**Comment by Marrekko** [comment]
Pierre,
first of all thank you so mich for this super fast answer!
Haha in fact I installed it manually on the Commando prompt using:

python setup.py install

on the newest SKC master folder downloaded from git. If thats not a proper way for installation I will try the pip way this afternoon and see if that fixes the Problem.

Big thanks again!

**Comment by yger** [comment]
You can install it like that, but then if you have multiple version of
python, be sure that you install with python3 and use with python3

Maybe you could try to do

>> pip uninstall spyking-circus
>> python3 setup.py install

Otherwise, if you install with pip/conda as said in the website, you will
get the proper version

Best

Pierre

**Comment by Marrekko** [comment]
Dear Pierre,

oh sorry, I totally forgot to answer. Your suggestion was completly  
right and I instantly began to work on my data. Thanks for the great  
support!

All the best for your projects!
Marek

Zitat von Pierre Yger <notifications@github.com>:
