### ISSUE TITLE
Assertion error in phy with sparse=True

### ISSUE THREAD

**Issue by yagui** [spyking-circus/spyking-circus#163]
I was having a problem trying to load my files into phy

```
  File "/home/ariel/virtualenvs/spyking/.spyking/lib/python3.6/site-packages/phy/apps/base.py", line 734, in __init__
    self.model = self._create_model(dir_path=dir_path, **kwargs) if model is None else model
  File "/home/ariel/virtualenvs/spyking/.spyking/lib/python3.6/site-packages/phy/apps/template/gui.py", line 84, in _create_model
    return TemplateModel(dir_path=dir_path, **kwargs)
  File "/home/ariel/virtualenvs/spyking/.spyking/lib/python3.6/site-packages/phylib/io/model.py", line 285, in __init__
    self._load_data()
  File "/home/ariel/virtualenvs/spyking/.spyking/lib/python3.6/site-packages/phylib/io/model.py", line 342, in _load_data
    self.sparse_templates = self._load_templates()
  File "/home/ariel/virtualenvs/spyking/.spyking/lib/python3.6/site-packages/phylib/io/model.py", line 619, in _load_templates
    assert cols.shape == (n_templates, n_channels_loc)
```

I updated spyking circus to the latest version. I re sorted my data, and now in the extracting step I'm getting this error
```
Extracting templates from already found clusters...
Traceback (most recent call last):
  File "/home/ariel/virtualenvs/spyking/.spyking/bin/spyking-circus-subtask", line 11, in <module>
    load_entry_point('spyking-circus==0.8.4', 'console_scripts', 'spyking-circus-subtask')()
  File "/home/ariel/virtualenvs/spyking/.spyking/lib/python3.6/site-packages/circus/scripts/subtask.py", line 43, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "/home/ariel/virtualenvs/spyking/.spyking/lib/python3.6/site-packages/circus/__init__.py", line 21, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "/home/ariel/virtualenvs/spyking/.spyking/lib/python3.6/site-packages/circus/extracting.py", line 45, in main
    clusters, spiketimes, N_clusters     = io.load_data(params, 'spike-cluster')
  File "/home/ariel/virtualenvs/spyking/.spyking/lib/python3.6/site-packages/circus/shared/files.py", line 983, in load_data
    raise Exception('Need to provide a spike-cluster file!')
Exception: Need to provide a spike-cluster file!
```
```

**Comment by yger** [comment]
Are you sure you want to launch the extracting step and not the converting
one ?

Because extracting is not really used, except if you have your own spine
times and want to get templates in order to perform the fitting. Is it what
you want to do?

Best

Pierre

Le jeu. 3 oct. 2019 à 18:57, Ariel Burman <notifications@github.com> a
écrit :

**Comment by yagui** [comment]
You are absolutely right. This was embarrassing XD
Now I keep having my initial problem, so I renamed the issue. 

```
Traceback (most recent call last):
  File "/home/ariel/virtualenvs/spyking/.spyking/bin/circus-gui-python", line 11, in <module>
    load_entry_point('spyking-circus==0.8.4', 'console_scripts', 'circus-gui-python')()
  File "/home/ariel/virtualenvs/spyking/.spyking/lib/python3.6/site-packages/circus/scripts/python_gui.py", line 184, in main
    controller = TemplateController(**gui_params)
  File "/home/ariel/virtualenvs/spyking/.spyking/lib/python3.6/site-packages/phy/apps/base.py", line 364, in __init__
    super(TemplateMixin, self).__init__(*args, **kwargs)
  File "/home/ariel/virtualenvs/spyking/.spyking/lib/python3.6/site-packages/phy/apps/base.py", line 734, in __init__
    self.model = self._create_model(dir_path=dir_path, **kwargs) if model is None else model
  File "/home/ariel/virtualenvs/spyking/.spyking/lib/python3.6/site-packages/phy/apps/template/gui.py", line 84, in _create_model
    return TemplateModel(dir_path=dir_path, **kwargs)
  File "/home/ariel/virtualenvs/spyking/.spyking/lib/python3.6/site-packages/phylib/io/model.py", line 285, in __init__
    self._load_data()
  File "/home/ariel/virtualenvs/spyking/.spyking/lib/python3.6/site-packages/phylib/io/model.py", line 342, in _load_data
    self.sparse_templates = self._load_templates()
  File "/home/ariel/virtualenvs/spyking/.spyking/lib/python3.6/site-packages/phylib/io/model.py", line 619, in _load_templates
    assert cols.shape == (n_templates, n_channels_loc)
```
This happens only when using "sparse_export=True".

**Comment by yger** [comment]
The sparse export works only with latest version of phy 2.0. Are you sure
your install is up to date?

>> pip install --upgrade
http://github.com/cortex-lab/phylib/archive/master.zip
>> pip install --upgrade http://github.com/cortex-lab/phy/archive/master.zip


Le jeu. 3 oct. 2019 à 20:27, Ariel Burman <notifications@github.com> a
écrit :

**Comment by yagui** [comment]
Yes, I'm using phy@dev (dev branch) and phylib

**Comment by yger** [comment]
Then I guess this is a bug to report on the phylib bug tracker. But maybe
you can also share with me your just your .GUI folder and your .params/.prb
such that I can try to reproduce the issue here.

Le jeu. 3 oct. 2019 à 20:56, Ariel Burman <notifications@github.com> a
écrit :

**Comment by yagui** [comment]
Do you need the (big) data file? or just the .GUI folder?

**Comment by yger** [comment]
The data file can be avoided. Just the .GUI folder to launch phy and
recreate the bug

Le ven. 4 oct. 2019 à 00:11, Ariel Burman <notifications@github.com> a
écrit :

**Comment by yger** [comment]
Any update? Please send me the data if you want me to have a look

**Comment by yagui** [comment]
I'm sorry, I tried to reproduce it and I was not able to do it.  I'll close this issue and if this problem appears again I'll try to be more precise about it.
