### ISSUE TITLE
polyorder must be less than window_length

### ISSUE THREAD

**Issue by rodriguez-facundo** [spyking-circus/spyking-circus#194]
Hi 👋,

I'm getting this error `polyorder must be less than window_length` and the algorithm hangs there. I think I have something misconfigured but I'm not really sure what that might be. The data is **Buzsaki hc-1 d533101.dat** (link [here](http://crcns.org/data-sets/hc/hc-1/about))

This is the params file

```ini
### Note that depending on the file format selected, the parameters in the data section can vary
### You should refer to the documentation to know what are the needed parameters for a given
### file format. Otherwise, launch the code and a message will tell you what is needed

[data]
file_format    = raw_binary           # Can be raw_binary, openephys, hdf5, ... See >> spyking-circus help -i for more info
stream_mode    = None       # None by default. Can be multi-files, or anything depending to the file format
mapping        = probe.py           # Mapping of the electrode (see http://spyking-circus.rtfd.ord)
suffix         =            # Suffix to add to generated files, if needed
overwrite      = True       # Filter or remove artefacts on site (if write access is possible). Data are duplicated otherwise
parallel_hdf5  = False       # Use the parallel HDF5 feature (if available)
output_dir     =            # By default, generated data are in the same folder as the data.

data_dtype     = int16
sampling_rate  = 10000
nb_channels    = 8

[detection]
radius         = auto       # Radius [in um] (if auto, read from the prb file)
N_t            = 3          # Width of the templates [in ms]
spike_thresh   = 6          # Threshold for spike detection
peaks          = negative   # Can be negative (default), positive or both
dead_channels  =            # If not empty or specified in the probe, a dictionary {channel_group : [list_of_valid_ids]}

[filtering]
cut_off        = 300, auto  # Min and Max (auto=nyquist) cut off frequencies for the band pass butterworth filter [Hz]
filter         = True       # If True, then a low-pass filtering is performed
remove_median  = False      # If True, median over all channels is substracted to each channels (movement artifacts)
common_ground  =            # If you want to use a particular channel as a reference ground: should be a channel number

[triggers]
trig_file      =            # External stimuli to be considered as putative artefacts [in trig units] (see documentation)
trig_windows   =            # The time windows of those external stimuli [in trig units]
trig_unit      = ms         # The unit in which times are expressed: can be ms or timestep
clean_artefact = False      # If True, external artefacts induced by triggers will be suppressed from data
dead_file      =            # Portion of the signals that should be excluded from the analysis [in dead units]
dead_unit      = ms         # The unit in which times for dead regions are expressed: can be ms or timestep
ignore_times   = False      # If True, any spike in the dead regions will be ignored by the analysis
make_plots     =            # Generate sanity plots of the averaged artefacts [Nothing or None if no plots]

[whitening]
spatial        = True       # Perform spatial whitening
max_elts       = 1000       # Max number of events per electrode (should be compatible with nb_elts)
nb_elts        = 0.8        # Fraction of max_elts that should be obtained per electrode [0-1]
output_dim     = 5          # Can be in percent of variance explain, or num of dimensions for PCA on waveforms

[clustering]
extraction     = median-raw # Can be either median-raw (default) or mean-raw
sub_dim        = 10         # Number of dimensions to keep for local PCA per electrode
max_elts       = 10000      # Max number of events per electrode (should be compatible with nb_elts)
nb_elts        = 0.8        # Fraction of max_elts that should be obtained per electrode [0-1]
nb_repeats     = 3          # Number of passes used for the clustering
smart_search   = True       # Activate the smart search mode
merging_method = distance   # Method to perform local merges (distance, dip, folding, nd-folding, bhatta)
merging_param  = default    # Merging parameter (see docs) (3 if distance, 0.5 if dip, 1e-9 if folding, 2 if bhatta)
sensitivity    = 3          # Single parameter for clustering sensitivity. The lower the more sensitive
cc_merge       = 0.95       # If CC between two templates is higher, they are merged
dispersion     = (5, 5)     # Min and Max dispersion allowed for amplitudes [in MAD]
make_plots     =            # Generate sanity plots of the clustering [Nothing or None if no plots]

[fitting]
amp_limits     = (0.3, 5)   # Amplitudes for the templates during spike detection [if not auto]
amp_auto       = True       # True if amplitudes are adjusted automatically for every templates
collect_all    = False      # If True, one garbage template per electrode is created, to store unfitted spikes

[merging]
erase_all      = True       # If False, a prompt will ask you to remerge if merged has already been done
cc_overlap     = 0.85       # Only templates with CC higher than cc_overlap may be merged
cc_bin         = 2          # Bin size for computing CC [in ms]
default_lag    = 5          # Default length of the period to compute dip in the CC [ms]
auto_mode      = 0.75       # Between 0 (aggressive) and 1 (no merging). If empty, GUI is launched
remove_noise   = True       # If True, meta merging will remove obvious noise templates (weak amplitudes)
noise_limit    = 0.75       # Amplitude at which templates are classified as noise
sparsity_limit = 0.75       # Sparsity level (in percentage) for selecting templates as putative noise (in [0, 1])
time_rpv       = 5          # Time [in ms] to consider for Refraction Period Violations (RPV) (0 to disable)
rpv_threshold  = 0.02       # Percentage of RPV allowed while merging
merge_drifts   = False      # Try to automatically merge drifts, i.e. non overlapping spiking neurons
drift_limit    = 0.1        # Distance for drifts. The higher, the more non-overlapping the activities should be

[converting]
erase_all      = True       # If False, a prompt will ask you to export if export has already been done
export_pcs     = prompt     # Can be prompt [default] or in none, all, some
export_all     = False      # If True, unfitted spikes will be exported as the last Ne templates
sparse_export  = True       # For recent versions of phy, and large number of templates/channels
prelabelling   = False      # If True, putative labels (good, noise, best, mua) are pre-assigned to neurons

[validating]
nearest_elec   = auto       # Validation channel (e.g. electrode closest to the ground truth cell)
max_iter       = 200        # Maximum number of iterations of the stochastic gradient descent (SGD)
learning_rate  = 1.0e-3     # Initial learning rate which controls the step-size of the SGD
roc_sampling   = 10         # Number of points to estimate the ROC curve of the BEER estimate
test_size      = 0.3        # Portion of the dataset to include in the test split
radius_factor  = 0.5        # Radius factor to modulate physical radius during validation
juxta_dtype    = uint16     # Type of the juxtacellular data
juxta_thresh   = 6          # Threshold for juxtacellular detection
juxta_valley   = False      # True if juxta-cellular spikes are negative peaks
juxta_spikes   =            # If none, spikes are automatically detected based on juxta_thresh
filter         = True       # If the juxta channel need to be filtered or not
make_plots     = png        # Generate sanity plots of the validation [Nothing or None if no plots]

[extracting]
safety_time    = 1          # Temporal zone around which spikes are isolated [in ms]
max_elts       = 1000       # Max number of collected events per templates
output_dim     = 5          # Percentage of variance explained while performing PCA
cc_merge       = 0.975      # If CC between two templates is higher, they are merged
noise_thr      = 0.8        # Minimal amplitudes are such than amp*min(templates) < noise_thr*threshold

[noedits]
filter_done    = True              #!! AUTOMATICALLY EDITED: DO NOT MODIFY !!
artefacts_done = False      # Will become True automatically after removing artefacts
median_done    = False      # Will become True automatically after removing common median
ground_done    = False      # Will become True automatically after removing common ground

```

This is the Probe file

```python
total_nb_channels = 8
radius            = 250

channel_groups = {
    # Shank index.
    0:
        {
            # List of channels to keep for spike detection.
            'channels': [2,3,4,5],

            # Adjacency graph. Dead channels will be automatically discarded
            # by considering the corresponding subgraph.
            'graph': [
                (0, 1),
                (1, 2),
                (2, 3),
                (3, 4),
                (4, 5),
                (5, 6),
                (6, 7)
            ],

            # 2D positions of the channels, only for visualization purposes
            # in KlustaViewa. The unit doesn't matter.
            'geometry': {
                7: (30, 0),
                6: (0, 30),
                5: (0, 20),
                4: (10, 20),
                3: (10, 10),
                2: (10, 0),
                1: (0, 10),
                0: (0, 0),
            }
    }
}

```

And this is the output

```log
➜ spyking-circus /Users/snakes/Desktop/Buzsaki/d5331/circus/d533101.dat -c=2

##################################################################
#####           Welcome to the SpyKING CIRCUS (0.8.9)        #####
#####                                                        #####
#####              Written by P.Yger and O.Marre             #####
##################################################################


File          : /Users/snakes/Desktop/Buzsaki/d5331/circus/d533101.dat
Steps         : filtering, whitening, clustering, fitting, merging
Number of CPU : 2/12
Parallel HDF5 : False
Shared memory : True
Hostfile      : /Users/snakes/spyking-circus/circus.hosts

##################################################################


-------------------------  Informations  -------------------------
| Number of recorded channels : 8
| Number of analyzed channels : 4
| File format                 : RAW_BINARY
| Data type                   : int16
| Sampling rate               : 10 kHz
| Duration of the recording   : 4 min 0 s 25 ms
| Width of the templates      : 3 ms
| Spatial radius considered   : 250 um
| Threshold crossing          : negative
------------------------------------------------------------------
-------------------------  Informations  -------------------------
| Using only 2 out of 12 local CPUs available (-c to change)
------------------------------------------------------------------
-------------------------  Informations  -------------------------
| Filtering has already been done
------------------------------------------------------------------
Analyzing data to get whitening matrices and thresholds...
Found 0.0001s without spikes for whitening matrices...
Because of whitening, need to recompute the thresholds...
Searching spikes to construct the PCA basis...
100%|████████████████████████████████████|[00:00<00:00,  4.40it/s]
Found 826 waveforms over 3200 requested
-------------------------  Informations  -------------------------
| A basis with 5 dimensions has been built
------------------------------------------------------------------
Searching random spikes to sample amplitudes...
100%|████████████████████████████████████|[00:00<00:00,  7.46it/s]
Found 845 spikes over 32000 requested
Estimating amplitudes distributions...
Smart Search of good isolated spikes for the clustering (1/3)...
100%|█████████████████████████████████|[00:00<00:00, 12446.01it/s]
Found 759 isolated spikes over 32000 requested (87 rejected)
Computing density estimations...
Searching random spikes to refine the clustering (2/3)...
100%|████████████████████████████████████|[00:00<00:00,  4.98it/s]
Found 86 spikes over 32000 requested
Refining density estimations...
Searching random spikes to refine the clustering (3/3)...
100%|████████████████████████████████████|[00:00<00:00,  4.71it/s]
Found 0 spikes over 32000 requested
-------------------------  Informations  -------------------------
| No more spikes in the recording, stop searching
------------------------------------------------------------------
Refining density estimations...
Running density-based clustering...
100%|██████████████████████████████████|[00:00<00:00, 9998.34it/s]
-------------------------  Informations  -------------------------
| Number of clusters found : 2
| Number of local merges   : 0 (method distance, param 3)
| Not enough spikes gathered: -put safety_space=False?
|                             -remove smart_search?
------------------------------------------------------------------
Estimating the templates with the median-raw procedure ...
100%|███████████████████████████████████|[00:00<00:00, 546.28it/s]
Traceback (most recent call last):
  File "/Users/snakes/miniconda3/envs/circus/bin/spyking-circus-subtask", line 8, in <module>
    sys.exit(main())
  File "/Users/snakes/miniconda3/envs/circus/lib/python3.6/site-packages/circus/scripts/subtask.py", line 47, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "/Users/snakes/miniconda3/envs/circus/lib/python3.6/site-packages/circus/__init__.py", line 21, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "/Users/snakes/miniconda3/envs/circus/lib/python3.6/site-packages/circus/clustering.py", line 964, in main
    tmp_fast = scipy.signal.savgol_filter(first_component, savgol_window, 3, axis=1)
  File "/Users/snakes/miniconda3/envs/circus/lib/python3.6/site-packages/scipy/signal/_savitzky_golay.py", line 337, in savgol_filter
    coeffs = savgol_coeffs(window_length, polyorder, deriv=deriv, delta=delta)
  File "/Users/snakes/miniconda3/envs/circus/lib/python3.6/site-packages/scipy/signal/_savitzky_golay.py", line 99, in savgol_coeffs
    raise ValueError("polyorder must be less than window_length.")
ValueError: polyorder must be less than window_length.
```

And the logs

```logs
2019-12-26 09:22:37,076 DEBUG    [circus.shared.parser] Creating a Circus Parser for datafile /Users/snakes/Desktop/Buzsaki/d5331/circus/d533101.dat
2019-12-26 09:22:37,079 DEBUG    [circus.shared.probes] Reading the probe file /Users/snakes/Desktop/Buzsaki/d5331/circus/probe.py
2019-12-26 09:22:37,090 DEBUG    [circus.shared.parser] Cluster not detected, so using global /tmp folder
2019-12-26 09:22:37,090 DEBUG    [circus.shared.parser] Hanning filtering is activated
2019-12-26 09:22:37,090 DEBUG    [circus.shared.parser] Trying to read file /Users/snakes/Desktop/Buzsaki/d5331/circus/d533101.dat as raw_binary
2019-12-26 09:22:37,091 DEBUG    [circus.files.datafile] data_dtype is read from the params with a value of int16
2019-12-26 09:22:37,091 DEBUG    [circus.files.datafile] sampling_rate is read from the params with a value of 10000.0
2019-12-26 09:22:37,091 DEBUG    [circus.files.datafile] nb_channels is read from the params with a value of 8
2019-12-26 09:22:37,091 DEBUG    [circus.files.datafile] dtype_offset is not set and has the default value of auto
2019-12-26 09:22:37,091 DEBUG    [circus.files.datafile] data_offset is not set and has the default value of 0
2019-12-26 09:22:37,091 DEBUG    [circus.files.datafile] gain is not set and has the default value of 1.0
2019-12-26 09:22:37,098 DEBUG    [circus.files.datafile] data type offset for int16 is automatically set to 0
2019-12-26 09:22:37,098 DEBUG    [circus.shared.parser] Changing all values in the param depending on the rate
2019-12-26 09:22:37,098 DEBUG    [circus.shared.parser] Trying to read file /Users/snakes/Desktop/Buzsaki/d5331/circus/d533101.dat as raw_binary
2019-12-26 09:22:37,099 DEBUG    [circus.files.datafile] data_dtype is read from the params with a value of int16
2019-12-26 09:22:37,099 DEBUG    [circus.files.datafile] sampling_rate is read from the params with a value of 10000.0
2019-12-26 09:22:37,099 DEBUG    [circus.files.datafile] nb_channels is read from the params with a value of 8
2019-12-26 09:22:37,099 DEBUG    [circus.files.datafile] dtype_offset is not set and has the default value of auto
2019-12-26 09:22:37,099 DEBUG    [circus.files.datafile] data_offset is not set and has the default value of 0
2019-12-26 09:22:37,099 DEBUG    [circus.files.datafile] gain is not set and has the default value of 1.0
2019-12-26 09:22:37,106 DEBUG    [circus.files.datafile] data type offset for int16 is automatically set to 0
2019-12-26 09:22:37,106 INFO     [circus.shared.files] Number of recorded channels : 8
2019-12-26 09:22:37,106 INFO     [circus.shared.files] Number of analyzed channels : 4
2019-12-26 09:22:37,106 INFO     [circus.shared.files] File format                 : RAW_BINARY
2019-12-26 09:22:37,106 INFO     [circus.shared.files] Data type                   : int16
2019-12-26 09:22:37,106 INFO     [circus.shared.files] Sampling rate               : 10 kHz
2019-12-26 09:22:37,106 INFO     [circus.shared.files] Duration of the recording   : 4 min 0 s 25 ms
2019-12-26 09:22:37,107 INFO     [circus.shared.files] Width of the templates      : 3 ms
2019-12-26 09:22:37,107 INFO     [circus.shared.files] Spatial radius considered   : 250 um
2019-12-26 09:22:37,107 INFO     [circus.shared.files] Threshold crossing          : negative
2019-12-26 09:22:37,107 DEBUG    [circus.shared.mpi] MPI detected: ('MPICH', (3, 3, 2))
2019-12-26 09:22:38,211 DEBUG    [circus.filtering] Initializing the filtering step...
2019-12-26 09:22:38,211 DEBUG    [circus.filtering] Reading the input file...
2019-12-26 09:22:38,211 DEBUG    [circus.shared.parser] Trying to read file /Users/snakes/Desktop/Buzsaki/d5331/circus/d533101.dat as raw_binary
2019-12-26 09:22:38,211 DEBUG    [circus.files.datafile] data_dtype is read from the params with a value of int16
2019-12-26 09:22:38,211 DEBUG    [circus.files.datafile] sampling_rate is read from the params with a value of 10000.0
2019-12-26 09:22:38,211 DEBUG    [circus.files.datafile] nb_channels is read from the params with a value of 8
2019-12-26 09:22:38,211 DEBUG    [circus.files.datafile] dtype_offset is not set and has the default value of auto
2019-12-26 09:22:38,211 DEBUG    [circus.files.datafile] data_offset is not set and has the default value of 0
2019-12-26 09:22:38,211 DEBUG    [circus.files.datafile] gain is not set and has the default value of 1.0
2019-12-26 09:22:38,228 DEBUG    [circus.files.datafile] data type offset for int16 is automatically set to 0
2019-12-26 09:22:38,228 DEBUG    [circus.shared.parser] Changing all values in the param depending on the rate
2019-12-26 09:22:38,228 INFO     [circus.filtering] Filtering has already been done
2019-12-26 09:22:38,425 DEBUG    [circus.shared.mpi] MPI detected: ('MPICH', (3, 3, 2))
2019-12-26 09:22:39,502 DEBUG    [circus.shared.mpi] Setting data chunk size to 30 second
2019-12-26 09:22:39,509 DEBUG    [circus.whitening] Analyzing data to get whitening matrices and thresholds...
2019-12-26 09:22:39,510 DEBUG    [circus.files.datafile] There are 8 chunks of size 300000
2019-12-26 09:22:39,510 DEBUG    [circus.files.datafile] The last chunk has size 256
2019-12-26 09:22:40,578 DEBUG    [circus.whitening] Found 0.0001s without spikes for whitening matrices...
2019-12-26 09:22:40,580 DEBUG    [circus.whitening] Because of whitening, need to recompute the thresholds...
2019-12-26 09:22:40,637 DEBUG    [circus.shared.mpi] Setting data chunk size to 120.013 second
2019-12-26 09:22:40,645 DEBUG    [circus.whitening] Searching spikes to construct the PCA basis...
2019-12-26 09:22:40,645 DEBUG    [circus.files.datafile] There are 2 chunks of size 1200128
2019-12-26 09:22:40,649 DEBUG    [circus.files.datafile] The last chunk has size 0
2019-12-26 09:22:40,881 DEBUG    [circus.whitening] Node 0 has collected 317 waveforms
2019-12-26 09:22:40,947 DEBUG    [circus.whitening] Node 1 has collected 509 waveforms
2019-12-26 09:22:40,947 DEBUG    [circus.whitening] Found 826 waveforms over 3200 requested
2019-12-26 09:22:40,958 INFO     [circus.whitening] A basis with 5 dimensions has been built
2019-12-26 09:22:40,959 DEBUG    [circus.whitening] The percentage of variance explained is 0.9998386474023557 for negative spikes
2019-12-26 09:22:41,149 DEBUG    [circus.shared.mpi] MPI detected: ('MPICH', (3, 3, 2))
2019-12-26 09:22:42,231 DEBUG    [circus.shared.mpi] Setting data chunk size to 120.013 second
2019-12-26 09:22:42,244 DEBUG    [circus.files.datafile] There are 2 chunks of size 1200128
2019-12-26 09:22:42,244 DEBUG    [circus.files.datafile] The last chunk has size 0
2019-12-26 09:22:42,244 DEBUG    [circus.clustering] Searching random spikes to sample amplitudes...
2019-12-26 09:22:42,817 DEBUG    [circus.clustering] Node 0 has collected 0 spikes and rejected 0 spikes
2019-12-26 09:22:42,817 DEBUG    [circus.clustering] Node 1 has collected 845 spikes and rejected 0 spikes
2019-12-26 09:22:42,817 DEBUG    [circus.clustering] Found 845 spikes over 32000 requested
2019-12-26 09:22:42,817 DEBUG    [circus.clustering] Estimating amplitudes distributions...
2019-12-26 09:22:42,817 DEBUG    [circus.clustering] Smart search is actived on channel 1
2019-12-26 09:22:42,818 DEBUG    [circus.clustering] Smart search is actived on channel 3
2019-12-26 09:22:42,818 DEBUG    [circus.clustering] Smart Search disabled on 2 electrodes
2019-12-26 09:22:42,818 DEBUG    [circus.clustering] Smart Search of good isolated spikes for the clustering (1/3)...
2019-12-26 09:22:42,818 DEBUG    [circus.clustering] Node 1 found not enough spikes: searching only 845 spikes instead of 16000
2019-12-26 09:22:42,818 DEBUG    [circus.clustering] Node 0 found not enough spikes: searching only 0 spikes instead of 16000
2019-12-26 09:22:43,402 DEBUG    [circus.clustering] Node 1 has collected 759 spikes and rejected 87 spikes
2019-12-26 09:22:43,402 DEBUG    [circus.clustering] Node 0 has collected 0 spikes and rejected 0 spikes
2019-12-26 09:22:43,402 DEBUG    [circus.clustering] Found 759 isolated spikes over 32000 requested (87 rejected)
2019-12-26 09:22:43,402 DEBUG    [circus.clustering] Computing density estimations...
2019-12-26 09:22:43,404 DEBUG    [circus.clustering] Node 1 will use temp file /Users/snakes/Desktop/Buzsaki/d5331/circus/d533101/d533101/tmp/tmp633n9t2a.hdf5
2019-12-26 09:22:43,404 DEBUG    [circus.clustering] Node 0 will use temp file /Users/snakes/Desktop/Buzsaki/d5331/circus/d533101/d533101/tmp/tmpa08uh6p8.hdf5
2019-12-26 09:22:43,405 DEBUG    [circus.clustering] The variance explained by local PCA on electrode 1 from 737 neg spikes is 0.999312 with 10 dimensions
2019-12-26 09:22:43,469 DEBUG    [circus.clustering] The variance explained by local PCA on electrode 3 from 22 neg spikes is 0.999393 with 10 dimensions
2019-12-26 09:22:43,471 DEBUG    [circus.clustering] Searching random spikes to refine the clustering (2/3)...
2019-12-26 09:22:43,681 DEBUG    [circus.clustering] Node 1 has collected 50 spikes and rejected 0 spikes
2019-12-26 09:22:43,681 DEBUG    [circus.clustering] Node 0 has collected 36 spikes and rejected 0 spikes
2019-12-26 09:22:43,681 DEBUG    [circus.clustering] Found 86 spikes over 32000 requested
2019-12-26 09:22:43,682 DEBUG    [circus.clustering] Refining density estimations...
2019-12-26 09:22:43,710 DEBUG    [circus.clustering] Searching random spikes to refine the clustering (3/3)...
2019-12-26 09:22:43,930 DEBUG    [circus.clustering] Node 0 has collected 0 spikes and rejected 0 spikes
2019-12-26 09:22:43,930 DEBUG    [circus.clustering] Node 1 has collected 0 spikes and rejected 0 spikes
2019-12-26 09:22:43,930 DEBUG    [circus.clustering] Found 0 spikes over 32000 requested
2019-12-26 09:22:43,930 INFO     [circus.clustering] No more spikes in the recording, stop searching
2019-12-26 09:22:43,930 DEBUG    [circus.clustering] Refining density estimations...
2019-12-26 09:22:43,931 DEBUG    [circus.clustering] Running density-based clustering...
2019-12-26 09:22:43,931 DEBUG    [circus.clustering] Node 0: not enough negative spikes on channel 0
2019-12-26 09:22:43,931 DEBUG    [circus.clustering] Node 0: not enough negative spikes on channel 2
2019-12-26 09:22:43,981 DEBUG    [circus.clustering] Node 1: 1-0 negative templates on channel 1 from 737 spikes: [737]
2019-12-26 09:22:43,986 DEBUG    [circus.clustering] Node 1: 1-0 negative templates on channel 3 from 22 spikes: [22]
2019-12-26 09:22:43,987 INFO     [circus.clustering] Number of clusters found : 2
2019-12-26 09:22:43,987 INFO     [circus.clustering] Number of local merges   : 0 (method distance, param 3)
2019-12-26 09:22:43,987 INFO     [circus.clustering] Not enough spikes gathered: -put safety_space=False?
2019-12-26 09:22:43,987 INFO     [circus.clustering]                             -remove smart_search?
2019-12-26 09:22:43,987 DEBUG    [circus.clustering] Estimating the templates with the median-raw procedure ...
2019-12-26 09:22:43,987 DEBUG    [circus.clustering] Templates will be smoothed by Savitzky Golay Filtering ...
```

**Comment by yger** [comment]
Yes, I know, this has been fixed in the master branch. Will be part of
0.9.0 that should be release soon. Meanwhile, you can try to upgrade the
software from git

>> pip install
https://github.com/spyking-circus/spyking-circus/archive/master.zip
--upgrade

Best

**Comment by rodriguez-facundo** [comment]
Thanks @yger,

I use this commit instead https://github.com/spyking-circus/spyking-circus/commit/756f6697b1266a77704dca60474eb4758bdf4c6a. I think master does not have it yet.

**Comment by sofiapuvogelvittini** [comment]
Hi, I'm experiencing something quite similar while using spykingcircus2 with SpikeInterface and Maxwell's MaxTwo data. I obtained the error "polyorder must be less than window_length".
Attached the log file.
Could you give me some advice please?
Thanks a lot!
[spikeinterface_log.json](https://github.com/spyking-circus/spyking-circus/files/14742555/spikeinterface_log.json)

**Comment by yger** [comment]
Maybe this can happen if your sampling rate is low. I'll make a fix soon. Meanwhile, you can avoid the error by setting run_sorter("spykingcircus2', clustering={"smoothing_kwargs": {"window_length_ms": 0.25, "order" : 1}}, ....)

**Comment by sofiapuvogelvittini** [comment]
Thanks, this allowed the algorithm to continue running. My sampling rate is 10000, is this low?

**Comment by yger** [comment]
This is low, but it should work. I'm more used to deal with 20/30kHz, but as said 10kHz should be fine

**Comment by yger** [comment]
In circus2, I've made a PR circus2_improvements that patches this issue

**Comment by sofiapuvogelvittini** [comment]
Hi, I included the seven files from the Circus2 improvements #2574 pull request.
But now I obtain the following error "cannot import name 'remove_empty_templates' from 'spikeinterface.sortingcomponents.tools' (attached a screenshot). 
[Error.pdf](https://github.com/spyking-circus/spyking-circus/files/14758761/Error.pdf)

Do you know how can I fix this?

Also, before adding the Circus2 improvements #2574 pull request, I was able to run spykingcircus2  in spikeinterface setting  "window_length_ms": 0.25, "order" : 1". However, after running:
 si.compute_quality_metrics(we, metric_names=metric_names, verbose=True,  qm_params=qm_params, **job_kwargs)
The amplitude-related columns were NaN values, Do you think this could be somehow related to setting window_length_ms": 0.25, "order" : 1? 
[qm.csv](https://github.com/spyking-circus/spyking-circus/files/14758780/qm.csv)

Thanks for your help!

**Comment by yger** [comment]
ok, then give me some time till tomorrow, and I'll check everything properly. But the error is strange, because the function should be present in main. It disapears if you switch back to main branch?

**Comment by sofiapuvogelvittini** [comment]
Thank you for taking time for this. 
I am not sure what do you mean by switch back to main branch, but indeed it works if I replace the corresponding files on the "Circus2 improvements #2574 pull request" for the original ones provided with spikeinterface installation (virtual environment), and adding "window_length_ms": 0.25, "order" : 1". The only extra change I have included to the spikeinterface-related files is: https://github.com/NeuralEnsemble/python-neo/pull/1444/files
This allowed to read MaxTwo data.

**Comment by yger** [comment]
Ok, so I double checked, and something must be fishy with your install. The remove_empty_templates() functions should be present in PR #2574, as shown here https://github.com/yger/spikeinterface/blob/circus2_improvements/src/spikeinterface/sortingcomponents/tools.py

Note that this PR should be added to the main branch, and not to 0.100 versions. This implies some major refactoring, and the code you are showing to compute the quality metrics will be deprecated now with the new object SortingAnalyzer. This is why I think there is some confusion going on about how your installed everything. If you do not want to adapt your code, simply set order=1 and this will do the jobs. The other improvements in the branch are mostly speed related, and/or low channels count
