### ISSUE TITLE
Pyqt required when no gui is used, master branch

### ISSUE THREAD

**Issue by yagui** [spyking-circus/spyking-circus#239]
I was using the latest pip version 0.9.6 and I tried the latest master branch version to test some fix.
Now it requires Pyqt5 although I'm not planning to use the gui interface (working on cluster)

I tested again in a fresh environment 
```
python install git+https://github.com/spyking-circus/spyking-circus --no-binary=mpi4py
```
The problem arise in the 'merging' step.
In #120 is described the same problem but I'm using auto_mode=0.75 (and it was working with the current pip version)

```
...
-------------------------  Informations  -------------------------
| Exporting data for the phy GUI with 10 CPUs...
------------------------------------------------------------------
100%|████████████████████████████████████|[00:35<00:00,  5.09s/it]
Traceback (most recent call last):
  File "/home/ariel/virtualenvs/spyking-test/.spc/lib/python3.6/site-packages/circus/shared/gui.py", line 15, in <module>
    from PyQt5 import uic
ModuleNotFoundError: No module named 'PyQt5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ariel/virtualenvs/spyking-test/.spc/bin/spyking-circus-subtask", line 11, in <module>
    load_entry_point('spyking-circus==0.9.7', 'console_scripts', 'spyking-circus-subtask')()
  File "/home/ariel/virtualenvs/spyking-test/.spc/lib/python3.6/site-packages/circus/scripts/subtask.py", line 53, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu, extension=extension)
  File "/home/ariel/virtualenvs/spyking-test/.spc/lib/python3.6/site-packages/circus/__init__.py", line 16, in launch
    module = importlib.import_module('circus.' + task)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ariel/virtualenvs/spyking-test/.spc/lib/python3.6/site-packages/circus/merging.py", line 2, in <module>
    from circus.shared import gui
  File "/home/ariel/virtualenvs/spyking-test/.spc/lib/python3.6/site-packages/circus/shared/gui.py", line 21, in <module>
    from matplotlib.backends.backend_qt4agg import NavigationToolbar2QT as NavigationToolbar
  File "/home/ariel/virtualenvs/spyking-test/.spc/lib/python3.6/site-packages/matplotlib/backends/backend_qt4agg.py", line 5, in <module>
    from .backend_qt5agg import (
  File "/home/ariel/virtualenvs/spyking-test/.spc/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 11, in <module>
    from .backend_qt5 import (
  File "/home/ariel/virtualenvs/spyking-test/.spc/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 15, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/home/ariel/virtualenvs/spyking-test/.spc/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 12, in <module>
    from matplotlib.backends.qt_compat import QtGui
  File "/home/ariel/virtualenvs/spyking-test/.spc/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 168, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding
Traceback (most recent call last):
  File "/home/ariel/virtualenvs/spyking-test/.spc/lib/python3.6/site-packages/circus/shared/gui.py", line 15, in <module>
    from PyQt5 import uic
ModuleNotFoundError: No module named 'PyQt5'
```

**Comment by yagui** [comment]
It is also failing in 0.9.6 from pipy

**Comment by yger** [comment]
I know that despite PyQt5 is not used, you must have it installed... I'll try to make it optional maybe, in future release, but as said since the preview GUI needs it, for now this is a mandatory requirement. What do you mean by "failing in 0.9.6"?

**Comment by yagui** [comment]
ok, I though that it was not required in the 0.9.6 that it is in pypi but I was wrong, installing pyqt5 was no problem and solved the issue.
