### ISSUE TITLE
Error in converting step

### ISSUE THREAD

**Issue by yagui** [spyking-circus/spyking-circus#240]
Hello again :)
I'm having this error in converting step. This was not happening before, and I'm not really sure what did I change, maybe you have a clue.
Thanks

```
-------------------------  Informations  -------------------------                                                                                                                                      
| Exporting data for the phy GUI with 35 CPUs...                                                                                                                                                        
------------------------------------------------------------------                                                                                                                                      
Traceback (most recent call last):                                                                                                                                                                      
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/bin/spyking-circus-subtask", line 8, in <module>                                                                                              
    sys.exit(main())                                                                                                                                                                                    
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/lib/python3.6/site-packages/circus/scripts/subtask.py", line 53, in main                                                                      
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu, extension=extension)                                                                                                                         
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/lib/python3.6/site-packages/circus/__init__.py", line 21, in launch                                                                           
    module.main(params, nb_cpu, nb_gpu, use_gpu, extension)                                                                                                                                             
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/lib/python3.6/site-packages/circus/converting.py", line 369, in main                                                                          
    write_results(output_path, params, extension)                                                                                                                                                       
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/lib/python3.6/site-packages/circus/converting.py", line 75, in write_results                                                                  
    result = io.get_results(params, extension)                                                                                                                                                          
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/lib/python3.6/site-packages/circus/shared/files.py", line 1751, in get_results                                                                
    myfile = h5py.File(file_out_suff + '.result%s.hdf5' % extension, 'r', libver='earliest')                                                                                                            
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__                                                                         
    swmr=swmr)                                                                                                                                                                                          
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/lib/python3.6/site-packages/h5py/_hl/files.py", line 173, in make_fid                                                                         
    fid = h5f.open(name, flags, fapl=fapl)                                                                                                                                                              
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper                                                                                                                                 
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper                                                                                                                                 
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open                                                                                                                                                        
OSError: Unable to open file (unable to open file: name = '/home/gridsan/aburman/test/TonyB200227/spc-ompi/out/continuous.result.hdf5', errno = 2, error message = 'No such file or directory', flags = 
0, o_flags = 0)
```

**Comment by yagui** [comment]
is attempting to open the file `out/continuous.result.hdf5` but that file is not present.
When should it be generated?
I'm running the following line
```
spyking-circus continuous.dat -c 35 -m filtering,whitening,clustering,merging,converting
```

**Comment by yger** [comment]
You forgot the main step, i,e. the fitting step, in between clustering and
merging

>

**Comment by yagui** [comment]
Indeed. Thanks!
