### ISSUE TITLE
Error in converting step

### ISSUE THREAD

**Issue by yagui** [spyking-circus/spyking-circus#241]
Now I'm having the following error (it is there multiple times because running with multiple cores, but each error has a different index number (72 or 68) over the same total (55).
This happens only when using the option export_all = True

```
Traceback (most recent call last):
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/bin/spyking-circus-subtask", line 8, in <module>
    sys.exit(main())
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/lib/python3.6/site-packages/circus/scripts/subtask.py", line 53, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu, extension=extension)
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/lib/python3.6/site-packages/circus/__init__.py", line 21, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu, extension)
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/lib/python3.6/site-packages/circus/converting.py", line 421, in main
    write_pcs(output_path, params, extension, N_tm, make_pcs)
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/lib/python3.6/site-packages/circus/converting.py", line 310, in write_pcs
    indices = numpy.where(supports[target])[0]
IndexError: index 72 is out of bounds for axis 0 with size 55
Traceback (most recent call last):
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/bin/spyking-circus-subtask", line 8, in <module>
    sys.exit(main())
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/lib/python3.6/site-packages/circus/scripts/subtask.py", line 53, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu, extension=extension)
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/lib/python3.6/site-packages/circus/__init__.py", line 21, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu, extension)
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/lib/python3.6/site-packages/circus/converting.py", line 421, in main
    write_pcs(output_path, params, extension, N_tm, make_pcs)
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/lib/python3.6/site-packages/circus/converting.py", line 310, in write_pcs
    indices = numpy.where(supports[target])[0]
IndexError: index 68 is out of bounds for axis 0 with size 55
```

**Comment by yger** [comment]
Thanks for the feedback, I'll have a look.

**Comment by yger** [comment]
Are you sure you are not mixing up some results? The error is happening on a fresh new launch of the complete pipeline?

**Comment by yagui** [comment]
I tested it again in this condition
python 3.7 (also with 3.6), spyking-circus from master branch
dataset:
https://github.com/kwikteam/phy-data/blob/master/template/sim_binary.dat
probe file
```
total_nb_channels = 34
radius            = 1.5

channel_groups = {
    1: {
        'channels': list(range(34)),
        'graph' : [],
        'geometry': {
              7: [ 1,  0],
              9: [ 0,  1],
             11: [ 0,  2],
             13: [ 1,  2],
             15: [ 0,  3],
             17: [ 1,  3],
             19: [ 0,  4],
             21: [ 1,  4],
             23: [ 0,  5],
             25: [ 1,  5],
             27: [ 0,  6],
             29: [ 1,  6],
             31: [ 0,  7],
              6: [ 1,  7],
              8: [ 0,  8],
             10: [ 1,  8],
             12: [ 1,  9],
             14: [ 0, 10],
             16: [ 1, 10],
             18: [ 0, 11],
             20: [ 1, 11],
             22: [ 0, 12],
             24: [ 1, 12],
             26: [ 0, 13],
             28: [ 1, 13],
             30: [ 0, 14],
              0: [ 1, 14],
              1: [ 0, 15],
              2: [ 1, 15],
              3: [ 0, 16],
              4: [ 1, 16],
              5: [ 0, 17],
             32: [ 0, 30],
             33: [ 1, 30]
        }
    }
}
```
params
[sim_binary.params.txt](https://github.com/spyking-circus/spyking-circus/files/4447976/sim_binary.params.txt)

command
```
spyking-circus sim_binary.dat -c 1 -m filtering,whitening,clustering,fitting,merging,converting
```
I tried only one core to discard any problem with open mpi

error
```
-------------------------  Informations  -------------------------                                                                                                                                      
| Number of spikes fitted : 2115                                                                                                                                                                        
| Number of spikes not fitted (roughly): 423 [20 percent]                                                                                                                                               
------------------------------------------------------------------                                                                                                                                      
-------------------------  Informations  -------------------------
| Exporting data for the phy GUI with 1 CPUs...
------------------------------------------------------------------        
-------------------------  Informations  -------------------------
| Last 32 templates are unfitted spikes on all electrodes                                                                                                                                               ------------------------------------------------------------------                                                                                                                                       45%|_________________                   |[00:01<00:01, 19.55it/s]                                                                                              
Traceback (most recent call last):                                
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/bin/spyking-circus-subtask", line 8, in <module>
    sys.exit(main())                    
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/lib/python3.7/site-packages/circus/scripts/subtask.py", line 53, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu, extension=extension)
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/lib/python3.7/site-packages/circus/__init__.py", line 21, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu, extension)
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/lib/python3.7/site-packages/circus/converting.py", line 421, in main
    write_pcs(output_path, params, extension, N_tm, make_pcs)
  File "/home/gridsan/aburman/miniconda3/envs/spyking-dev/lib/python3.7/site-packages/circus/converting.py", line 310, in write_pcs
    indices = numpy.where(supports[target])[0]
IndexError: index 26 is out of bounds for axis 0 with size 26
-------------------------------------------------------
```

**Comment by yger** [comment]
Thanks, I'll have a look asap this morning and patch that

**Comment by yger** [comment]
This has been fixed by in the master branch, thanks for reporting

**Comment by yagui** [comment]
Thanks
