### ISSUE TITLE
Error when exporting unfitted spikes to Phy2

### ISSUE THREAD

**Issue by bapungiri** [spyking-circus/spyking-circus#244]
Hi,
The algorithm runs fine when I set '[fitting] collect all' and '[converting] export_all' to True, but seeing an error when trying to export it for visualization in Phy2.

Spyking Circus version: 0.9.6

Error:
-------------------------  Informations  -------------------------
| Last 16 templates are unfitted spikes on all electrodes
------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bapung/conda3/envs/circus/bin/spyking-circus-subtask", line 11, in <module>
    load_entry_point('spyking-circus==0.9.6', 'console_scripts', 'spyking-circus-subtask')()
  File "/home/bapung/conda3/envs/circus/lib/python3.6/site-packages/circus/scripts/subtask.py", line 53, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu, extension=extension)
  File "/home/bapung/conda3/envs/circus/lib/python3.6/site-packages/circus/__init__.py", line 21, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu, extension)
  File "/home/bapung/conda3/envs/circus/lib/python3.6/site-packages/circus/converting.py", line 371, in main
    N_tm = write_templates(output_path, params, extension)
  File "/home/bapung/conda3/envs/circus/lib/python3.6/site-packages/circus/converting.py", line 208, in write_templates
    waveform = io.get_stas(params, times_i=spikes, labels_i=np.ones(len(spikes)), src=elec, neighs=[elec], nodes=nodes, mean_mode=True)
  File "/home/bapung/conda3/envs/circus/lib/python3.6/site-packages/circus/shared/files.py", line 133, in get_stas
    local_chunk = data_file.get_snippet(time - offset, duration, nodes=nodes)
  File "/home/bapung/conda3/envs/circus/lib/python3.6/site-packages/circus/files/datafile.py", line 462, in get_snippet
    return self.get_data(0, chunk_size=length, padding=(local_time, local_time), nodes=nodes)[0]
  File "/home/bapung/conda3/envs/circus/lib/python3.6/site-packages/circus/files/datafile.py", line 471, in get_data
    return self.read_chunk(idx, chunk_size, padding, nodes), self.t_start + idx*chunk_size
  File "/home/bapung/conda3/envs/circus/lib/python3.6/site-packages/circus/files/raw_binary.py", line 53, in read_chunk
    local_chunk = self.data[t_start*self.nb_channels:t_stop*self.nb_channels]
  File "/home/bapung/conda3/envs/circus/lib/python3.6/site-packages/numpy/core/memmap.py", line 331, in __getitem__
    res = super(memmap, self).__getitem__(index)
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by yger** [comment]
Yes, this has been corrected in the master branch (0.9.7)
You can install it with
>>https://github.com/spyking-circus/spyking-circus/archive/master.zip
--upgrade

**Comment by bapungiri** [comment]
Great! Closing this issue now.
