### ISSUE TITLE
MPI problems

### ISSUE THREAD

**Issue by benefron** [spyking-circus/spyking-circus#255]
Hi I am trying to run the algorithm and I get the following error:

| Intel MPI may not be yet properly implemented: contact developpers
------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\lampllab\.conda\envs\circus\Scripts\spyking-circus-script.py", line 11, in <module>
    load_entry_point('spyking-circus==0.9.7', 'console_scripts', 'spyking-circus')()
  File "C:\Users\lampllab\.conda\envs\circus\lib\site-packages\circus\scripts\launch.py", line 428, in main
    subprocess.check_call(mpi_args)
  File "C:\Users\lampllab\.conda\envs\circus\lib\subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\lampllab\.conda\envs\circus\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\lampllab\.conda\envs\circus\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\lampllab\.conda\envs\circus\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

I pip installed the mpi4py and did not get the error specified in the documentation.
I am not sure what else to install and how.
would appriciate the help.
Thanks

**Comment by yger** [comment]
I guess, on windows, the safest is to install everything with conda. Did you followed the steps here
https://spyking-circus.readthedocs.io/en/latest/introduction/windows.html

Once this is done, you can upgrade to 0.9.8, since there was a bug in packaging, not released yet
>> pip install --upgrade https://github.com/spyking-circus/spyking-circus/archive/master.zip

This should work

**Comment by benefron** [comment]
solved thanks
