### ISSUE TITLE
out of bounds error during clustering_by_density

### ISSUE THREAD

**Issue by tbenst** [spyking-circus/spyking-circus#279]
Sadly the run crashed. I guess 32 million spikes is bound to find some edge cases ;)

<details>
<summary>output</summary>

<p>

```bash
##################################################################
#####           Welcome to the SpyKING CIRCUS (0.9.9)        #####
#####                                                        #####
#####              Written by P.Yger and O.Marre             #####
##################################################################


File          : /data/R1_E5.brw
Steps         : filtering, whitening, clustering, fitting, merging
Number of CPU : 8/16
Parallel HDF5 : True
Shared memory : True
Hostfile      : /home/tyler/spyking-circus/circus.hosts

##################################################################


-------------------------  Informations  -------------------------
| Number of recorded channels : 4096
| Number of analyzed channels : 4096
| File format                 : BRW
| Data type                   : uint16
| Sampling rate               : 17 kHz
| Duration of the recording   : 80 min 0 s 0 ms
| Width of the templates      : 3 ms
| Spatial radius considered   : 200 um
| Threshold crossing          : negative
------------------------------------------------------------------
-------------------------  Informations  -------------------------
| Using only 8 out of 16 local CPUs available (-c to change)
------------------------------------------------------------------
Filtering with a Butterworth filter (order 3) in [300, 8474.35] Hz
100%|█████████████████████████████████|[3:12:27<00:00, 102.19s/it]
Analyzing data to get whitening matrices and thresholds...
Found 3.64054s without spikes for whitening matrices...
Because of whitening, need to recompute the thresholds...
Searching spikes to construct the PCA basis...
100%|██████████████████████████████████|[2:49:24<00:00, 45.99s/it]
Found 3276800 waveforms over 3276800 requested
-------------------------  Informations  -------------------------
| A basis with 5 dimensions has been built
------------------------------------------------------------------
Searching isolated random spikes to sample amplitudes...
100%|████████████████████████████████|[10:12:16<00:00, 248.22s/it]
Found 10868385 spikes over 32768000 requested
Estimating amplitudes distributions...
Smart Search of good isolated spikes for the clustering (1/3)...
100%|████████████████████████████████|[10:15:34<00:00, 249.55s/it]
Found 9966328 isolated spikes over 32768000 requested (1927137 rejected)
Computing density estimations...
Searching random spikes to refine the clustering (2/3)...
100%|████████████████████████████████|[10:12:51<00:00, 248.46s/it]
Found 1390886 spikes over 32768000 requested
Refining density estimations...
Searching random spikes to refine the clustering (3/3)...
100%|████████████████████████████████|[10:09:21<00:00, 247.04s/it]
Found 292084 spikes over 32768000 requested
Refining density estimations...
Running density-based clustering...
 55%|███████████████████▊                |[01:58<01:37,  2.38it/s]
Traceback (most recent call last):
  File "/nix/store/qm3g0c7r8a6cf40f8j857xc3wshlwmm4-spyking-circus-0.9.9/bin/.spyking-circus-subtask-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/qm3g0c7r8a6cf40f8j857xc3wshlwmm4-spyking-circus-0.9.9/lib/python3.8/site-packages/circus/scripts/subtask.py", line 55, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "/nix/store/qm3g0c7r8a6cf40f8j857xc3wshlwmm4-spyking-circus-0.9.9/lib/python3.8/site-packages/circus/__init__.py", line 23, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "/nix/store/qm3g0c7r8a6cf40f8j857xc3wshlwmm4-spyking-circus-0.9.9/lib/python3.8/site-packages/circus/clustering.py", line 1130, in main
    c = numpy.delete(c, to_remove)  # update the cluster labels
  File "<__array_function__ internals>", line 5, in delete
  File "/nix/store/f3hkh242r5vf8wqwi3is2svpjrc69vmm-python3.8-numpy-1.19.1/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4406, in delete
    keep[obj,] = False
IndexError: index 0 is out of bounds for axis 0 with size 0
Traceback (most recent call last):
  File "/nix/store/qm3g0c7r8a6cf40f8j857xc3wshlwmm4-spyking-circus-0.9.9/bin/.spyking-circus-subtask-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/qm3g0c7r8a6cf40f8j857xc3wshlwmm4-spyking-circus-0.9.9/lib/python3.8/site-packages/circus/scripts/subtask.py", line 55, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "/nix/store/qm3g0c7r8a6cf40f8j857xc3wshlwmm4-spyking-circus-0.9.9/lib/python3.8/site-packages/circus/__init__.py", line 23, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "/nix/store/qm3g0c7r8a6cf40f8j857xc3wshlwmm4-spyking-circus-0.9.9/lib/python3.8/site-packages/circus/clustering.py", line 1130, in main
    c = numpy.delete(c, to_remove)  # update the cluster labels
  File "<__array_function__ internals>", line 5, in delete
  File "/nix/store/f3hkh242r5vf8wqwi3is2svpjrc69vmm-python3.8-numpy-1.19.1/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4406, in delete
    keep[obj,] = False
IndexError: index 3 is out of bounds for axis 0 with size 3
```

</p>

</details>

The crash occurs on this line: https://github.com/spyking-circus/spyking-circus/blob/cdcdef658ac39f9573bc83b48e1d0b27313cd4dc/circus/clustering.py#L1135

`c`, in turn, comes from this call (assigned to `centers`): https://github.com/spyking-circus/spyking-circus/blob/20fa32e73e92bfcb042e0abd315bed99ae5ae2f0/circus/shared/algorithms.py#L196

but if I had to take an educated guess, I think this line may be the culprit:
https://github.com/spyking-circus/spyking-circus/blob/20fa32e73e92bfcb042e0abd315bed99ae5ae2f0/circus/shared/algorithms.py#L198

The count of `centers - 1 >= 0` is not necessarily greater than or equal to the number of clusters if I understand correctly.

Unfortunately, the last checkpoint was 43 hours of compute ago so not sure how to test & debug this.

**Comment by yger** [comment]
I made a putative patch in master, that should work hopefully. As you are pointing out, if some electrodes do not find any clusters (which is rare, but can happen), then there could be a shape mistmach leading to an error. With old versions of numpy, this shape mismatch was ignored, but now seems that it is raising an error

**Comment by yger** [comment]
Solved in master branch
