### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by sv-bio** [spyking-circus/spyking-circus#347]
Dear Pierre,

Just updated to v. 1.0.7 and got the following error:

Computing optimal amplitudes for the templates...
100%|████████████████████████████████████|[00:12<00:00,  1.85it/s]
100%|████████████████████████████████████|[00:09<00:00,  4.68s/it]
Traceback (most recent call last):
  File "/home/user/miniconda2/envs/circus/bin/spyking-circus-subtask", line 33, in <module>
    sys.exit(load_entry_point('spyking-circus==1.0.7', 'console_scripts', 'spyking-circus-subtask')())
  File. "/home/user/miniconda2/envs/circus/lib/python3.6/site-packages/circus/scripts/subtask.py", line 54, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "/home/user/miniconda2/envs/circus/lib/python3.6/site-packages/circus/__init__.py", line 23, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "/home/user/miniconda2/envs/circus/lib/python3.6/site-packages/circus/clustering.py", line 1803, in main
    normalization=templates_normalization, debug_plots=debug_plots
  File "/home/user/miniconda2/envs/circus/lib/python3.6/site-packages/circus/shared/algorithms.py", line 1321, in refine_amplitudes
    max_amp = 1.25*very_good_values.max()
  File "/home/user/miniconda2/envs/circus/lib/python3.6/site-packages/numpy/core/_methods.py", line 39, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity

**----------------------------  Error  -----------------------------
| Step "clustering" failed for reason Command '['mpiexec', '-np', '4', 'spyking-circus-subtask', 'clustering', '/media/user/path/to/data/data.dat', '4', '0', 'False', 'False']' returned non-zero exit status 1.!
------------------------------------------------------------------**

My params are:

[clustering_params.txt](https://github.com/spyking-circus/spyking-circus/files/6135236/sbpro_1__uid0922-17-02-38.txt)

UPD: this problem appears sporadically

**UPD2**: when changes in algorithms.py from 5.02.2021 were undone, error disappeared.

**Comment by sv-bio** [comment]
UPD 3: Addition of max_amplitude = auto to "clustering" section of *.params file seems to solve this issue
