### ISSUE TITLE
Error message from spyking-circus

### ISSUE THREAD

**Issue by Hugues1273** [spyking-circus/spyking-circus#355]
Dear all, 

first, I m sorry for my English.
Yesterday I was trying to launch circus-gui-python as I used to do since a couple of weeks. Unusually, I get the following error message:
`[43520:48436:0511/193313.335:ERROR:network_service_instance_impl.cc(262)] Network service crashed, restarting service.`
Gui started but nothing appeared in it, the views windows were empty.

So I tried ti deinstall and install again spyking-circus and phy.
And then I got the following error message:
```
(circus) C:\Users\lamot\OneDrive\Documents\ThesisProject\Data\Raw\DiagDiffTourette\DystoniaRawData\RawExtensionFilesForSpykingCircusAnalysesDystonia\CDEV_GPI>spyking-circus CDEV_GPI_123_48000_sec12_-4.54.params -m converting
Traceback (most recent call last):
  File "C:\Users\lamot\anaconda3\envs\circus\Scripts\spyking-circus-script.py", line 33, in <module>
    sys.exit(load_entry_point('spyking-circus==1.0.7', 'console_scripts', 'spyking-circus')())
  File "C:\Users\lamot\anaconda3\envs\circus\Scripts\spyking-circus-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\lamot\anaconda3\envs\circus\lib\site-packages\importlib_metadata\__init__.py", line 166, in load
    module = import_module(match.group('module'))
  File "C:\Users\lamot\anaconda3\envs\circus\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\lamot\anaconda3\envs\circus\lib\site-packages\circus\scripts\launch.py", line 21, in <module>
    import h5py
  File "C:\Users\lamot\anaconda3\envs\circus\lib\site-packages\h5py\__init__.py", line 34, in <module>
    from . import version
  File "C:\Users\lamot\anaconda3\envs\circus\lib\site-packages\h5py\version.py", line 17, in <module>
    from . import h5 as _h5
  File "h5py\h5.pyx", line 1, in init h5py.h5
ImportError: DLL load failed: The specified procedure could not be found.
```
I already found a similar issue in this forum. I followed what was said, but I have still the same message error... :( I m too saaaaad!

If someone knows how to manage this issue, I would be happy to know how to fix it!

Thank you so much!

Hugues

**Comment by yger** [comment]
Not an expert here but this means that h5py is not properly installed. How did you install the software? Via pip? If so, then do
>> pip uninstall h5py (as many times as needed to remove all conflicting version)
Then
>> pip install h5py

If via conda, do
>> conda upgrade h5py to install a more recent version

**Comment by Hugues1273** [comment]
thank you for your rapid answer!

Well, I already tried it, it did not work. Therefore, I try again to install spyking circus. I get this following error message:
ERROR conda.core.link:_execute(698): An error occurred while installing package 'conda-forge::qt-5.12.9-h5909a2a_4'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::qt-5.12.9-h5909a2a_4
location of failed script: C:\Users\lamot\anaconda3\envs\circus\Scripts\.qt-post-link.bat
```
==> script messages <==
<None>
==> script output <==
stdout:
stderr:
return code: 255
```
Then I decided to begin again since the beginning so I uninstall spyking-circus and anaconda, and I followed the protocol of installation since the beginning but now, the same error message persists with the installation of this conda-forge package who failed. I m disgusted because all was working good since the very first error message that never happened... :(

I m so sorry. Would you know how to fix this? I thought about reset my computer but it is a lot just for fixing this error

Than you again!

**Comment by yger** [comment]
Out of the blue, like that, I don't know how to fix that, but I could give it a try via teamviewer maybe. Or I'll try to make a new install in a VM and see if this can be reproduced. For now, since the error is now related to qt simply do
conda upgrade qt
I just check in my windows VM, and I have qt 5.9.7 from the anaconda channel. Try to install it?
conda upgrade qt -c anaconda (if the channel is not found)

**Comment by Hugues1273** [comment]
Thank you so much. I updated qt following your advice. I have a meeting now but I ll will try again to install Spyking-Circus with this update version of qt. If it does not work, I will reset my computer and try again.

If it still does not work, would it be possible to come to the institut de la vision, I m working at the ICM with Katia Lehongre so I am your "voisin", so if you had so minutes for me it would be great, but first I 'll try to install it again now I have this updated qt and then, I ll try to reset windows (some people said to me maybe the original problem could come from the updates of windows, as I m not an expert in computer I will try to follow their advices!)

Whatever, I let you know!

**Comment by yger** [comment]
Yes, of course, I'll be there on Friday if needed

**Comment by Hugues1273** [comment]
I try to update qt but Spyking-Circus still did not work, I installed it again but the error message appeared. Then I tried to reset my computer and than install again Spyking-Circus but I have again this exactly same message error.

```
ERROR conda.core.link:_execute(698): An error occurred while installing package 'conda-forge::qt-5.12.9-h5909a2a_4'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::qt-5.12.9-h5909a2a_4
location of failed script: C:\Users\lamot\anaconda3\envs\circus\Scripts\.qt-post-link.bat

==> script messages <==
<None>
==> script output <==
stdout:
stderr:
return code: 255
```

When I try pip install, I have a huge error message:

```
  Building wheel for blosc (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\lamot\Anaconda3\envs\circus\python.exe' 'C:\Users\lamot\Anaconda3\envs\circus\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\lamot\AppData\Local\Temp\tmp5n9nxztq'
       cwd: C:\Users\lamot\AppData\Local\Temp\pip-install-t74qwrbi\blosc_8684fdc220c34387823b831d0e53a527
  Complete output (162 lines):
  Not searching for unused variables given on the command line.
  -- The C compiler identification is unknown
  CMake Error at CMakeLists.txt:3 (ENABLE_LANGUAGE):
    No CMAKE_C_COMPILER could be found.

    Tell CMake where to find the compiler by setting either the environment
    variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
    the compiler, or to the compiler name if it is in the PATH.


  -- Configuring incomplete, errors occurred!
  See also "C:/Users/lamot/AppData/Local/Temp/pip-install-t74qwrbi/blosc_8684fdc220c34387823b831d0e53a527/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  See also "C:/Users/lamot/AppData/Local/Temp/pip-install-t74qwrbi/blosc_8684fdc220c34387823b831d0e53a527/_cmake_test_compile/build/CMakeFiles/CMakeError.log".
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      Visual Studio 15 2017 Win64

    could not find any instance of Visual Studio.



  -- Configuring incomplete, errors occurred!
  See also "C:/Users/lamot/AppData/Local/Temp/pip-install-t74qwrbi/blosc_8684fdc220c34387823b831d0e53a527/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  Not searching for unused variables given on the command line.
  -- The C compiler identification is unknown
  CMake Error at CMakeLists.txt:3 (ENABLE_LANGUAGE):
    The CMAKE_C_COMPILER:

      cl

    is not a full path and was not found in the PATH.

    To use the NMake generator with Visual C++, cmake must be run from a shell
    that can use the compiler cl from the command line.  This environment is
    unable to invoke the cl compiler.  To fix this problem, run cmake from the
    Visual Studio Command Prompt (vcvarsall.bat).

    Tell CMake where to find the compiler by setting either the environment
    variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
    the compiler, or to the compiler name if it is in the PATH.


  -- Configuring incomplete, errors occurred!
  See also "C:/Users/lamot/AppData/Local/Temp/pip-install-t74qwrbi/blosc_8684fdc220c34387823b831d0e53a527/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  See also "C:/Users/lamot/AppData/Local/Temp/pip-install-t74qwrbi/blosc_8684fdc220c34387823b831d0e53a527/_cmake_test_compile/build/CMakeFiles/CMakeError.log".
  Not searching for unused variables given on the command line.
  -- The C compiler identification is unknown
  CMake Error at CMakeLists.txt:3 (ENABLE_LANGUAGE):
    The CMAKE_C_COMPILER:

      cl

    is not a full path and was not found in the PATH.

    To use the JOM generator with Visual C++, cmake must be run from a shell
    that can use the compiler cl from the command line.  This environment is
    unable to invoke the cl compiler.  To fix this problem, run cmake from the
    Visual Studio Command Prompt (vcvarsall.bat).

    Tell CMake where to find the compiler by setting either the environment
    variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
    the compiler, or to the compiler name if it is in the PATH.


  -- Configuring incomplete, errors occurred!
  See also "C:/Users/lamot/AppData/Local/Temp/pip-install-t74qwrbi/blosc_8684fdc220c34387823b831d0e53a527/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  See also "C:/Users/lamot/AppData/Local/Temp/pip-install-t74qwrbi/blosc_8684fdc220c34387823b831d0e53a527/_cmake_test_compile/build/CMakeFiles/CMakeError.log".


  --------------------------------------------------------------------------------
  -- Trying "Ninja (Visual Studio 15 2017 Win64 v141)" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja (Visual Studio 15 2017 Win64 v141)" generator - failure
  --------------------------------------------------------------------------------



  --------------------------------------------------------------------------------
  -- Trying "Visual Studio 15 2017 Win64 v141" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Visual Studio 15 2017 Win64 v141" generator - failure
  --------------------------------------------------------------------------------



  --------------------------------------------------------------------------------
  -- Trying "NMake Makefiles (Visual Studio 15 2017 Win64 v141)" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "NMake Makefiles (Visual Studio 15 2017 Win64 v141)" generator - failure
  --------------------------------------------------------------------------------



  --------------------------------------------------------------------------------
  -- Trying "NMake Makefiles JOM (Visual Studio 15 2017 Win64 v141)" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "NMake Makefiles JOM (Visual Studio 15 2017 Win64 v141)" generator - failure
  --------------------------------------------------------------------------------

  ********************************************************************************
  scikit-build could not get a working generator for your system. Aborting build.

  Building windows wheels for Python 3.6 requires Microsoft Visual Studio 2017.
  Get it with "Visual Studio 2017":

    https://visualstudio.microsoft.com/vs/

  ********************************************************************************
  ----------------------------------------
  ERROR: Failed building wheel for blosc
Failed to build blosc
ERROR: Could not build wheels for blosc which use PEP 517 and cannot be installed directly
```
I had exactly the same message before the reset of my computer. Therefore, now, I m definitively desperate... :(

But I am okay to come to see you, maybe you would find the solution! I m at the hospital till the end of this week and then on holidays. Would it be possible the week of the 31 of may? 

Thank you so much!

Hugues

**Comment by Hugues1273** [comment]
a detail, of course I tried to install windows visual studio but changed nothing to the message error coming from pip install...

**Comment by yger** [comment]
Did you managed to get somewhere? We can skype/zoom tomorrow if you want

**Comment by Hugues1273** [comment]
it's really kind! I m on holidays this week! next week I would be available, or any other week! I m availbale every days except on friday and saturday as I have my consultations.

Thank you so much!
