### ISSUE TITLE
configparser error

### ISSUE THREAD

**Issue by wuffi** [spyking-circus/spyking-circus#363]
On Windows 10 in a `circus` `conda` environment, I get the following error message both for the latest development version from GitHub as well as for the version available from `-c spyking-circus`:
```
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\circus\Scripts\spyking-circus-script.py", line 33, in <module>
    sys.exit(load_entry_point('spyking-circus', 'console_scripts', 'spyking-circus')())
  File "c:\users\user\software\spyking-circus\build\lib\circus\scripts\launch.py", line 173, in main
    params = CircusParser(real_file)
  File "c:\users\user\software\spyking-circus\build\lib\circus\shared\parser.py", line 307, in __init__
    for (key, value) in self.parser.items(section):
  File "C:\Users\user\Anaconda3\envs\circus\lib\configparser.py", line 858, in items
    return [(option, value_getter(option)) for option in d.keys()]
  File "C:\Users\user\Anaconda3\envs\circus\lib\configparser.py", line 858, in <listcomp>
    return [(option, value_getter(option)) for option in d.keys()]
  File "C:\Users\user\Anaconda3\envs\circus\lib\configparser.py", line 855, in <lambda>
    section, option, d[option], d)
  File "C:\Users\user\Anaconda3\envs\circus\lib\configparser.py", line 394, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "C:\Users\user\Anaconda3\envs\circus\lib\configparser.py", line 444, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '% of max dtype) [0,1]'
```

**Comment by wuffi** [comment]
The error is caused by the usage of a `%` sign in a comment of the generated `*.param` file.

Removing the `%` sign or deleting the comment solves the problem.
