### ISSUE TITLE
Converting step fails

### ISSUE THREAD

**Issue by fbens47** [spyking-circus/spyking-circus#379]
Hi,

I got this error when launching the conversion script, my file is a `.rhd`.
```
TypeError: float() argument must be a string or a number, not 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/feral/.local/bin/spyking-circus-subtask", line 8, in <module>
    sys.exit(main())
  File "/home/feral/.local/lib/python3.9/site-packages/circus/scripts/subtask.py", line 52, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu, extension=extension)
  File "/home/feral/.local/lib/python3.9/site-packages/circus/__init__.py", line 21, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu, extension)
  File "/home/feral/.local/lib/python3.9/site-packages/circus/converting.py", line 367, in main
    numpy.save(os.path.join(output_path, 'channel_positions'), positions.astype(numpy.double))
ValueError: setting an array element with a sequence.
```

It seems to come from the reading of the `.prb` file. But I can't see what's wrong, as I was able to run the algorithm on my data.

Yours,

PS: probe is a microprobes FMA 32 channels:

```
total_nb_channels = 32
radius            = 100

channel_groups = {
    1: {
        'channels': list(range(32)),
        'graph' : [],
        'geometry': {
            0:  [    0.0,    0.0],
            1:  [ -400.0,    0.0],
            2:  [ -800.0,    0.0],
            3:  [-1200.0,    0.0],
            4:  [-1600,0,    0.0],
            5:  [-2000,0,    0.0],
            6:  [-2400.0,    0.0],
            7:  [-2800.0,    0.0],
            8:  [ +600.0,  346.4],
            9:  [ +200.0,  346.4],
            10: [ -200.0,  346.4],
            11: [ -600.0,  346.4],
            12: [-1000.0,  346.4],
            13: [-1400.0,  346.4],
            14: [-1800.0,  346.4],
            15: [-2200.0,  346.4],
            16: [    0.0,  692.8],
            17: [ -400.0,  692.8],
            18: [ -800.0,  692.8],
            19: [-1200.0,  692.8],
            20: [-1600.0,  692.8],
            21: [-2000.0,  692.8],
            22: [-2400.0,  692.8],
            23: [-2800.0,  692.8],
            24: [ +600.0, 1039.2],
            25: [ +200.0, 1039.2],
            26: [ -200.0, 1039.2],
            27: [ -600.0, 1039.2],
            28: [-1000.0, 1039.2],
            29: [-1400.0, 1039.2],
            30: [-2000.0, 1039.2],
            31: [-2400.0, 1039.2],
        }
    }
}
```

Flavien

**Comment by yger** [comment]
I'm not in front of a computer, but not sure the + sign are valid to
describe positive values. Just remove them?

Best

Pierre

**Comment by fbens47** [comment]
I tried both removing the plus signs, and rescaling to negative values. Same error after these attempts.

Best

Flavien

**Comment by fbens47** [comment]
Found it, at index 4 and 5, I wrote a coma instead of a point for decimal. Because of that, in `converting.py`, function `generate_mapping(probe)` the `positions` array was of `dtype=object`.

Thanks,

Close it.
