### ISSUE TITLE
IndexError in results view in python 3.5

### ISSUE THREAD

**Issue by beOn** [spyking-circus/spyking-circus#38]
Asking for the results view on an openephys dataset, I get the following error: 

```bash
Traceback (most recent call last):
  File "/Users/benacland/anaconda/envs/spykpi/bin/spyking-circus", line 11, in <module>
    load_entry_point('spyking-circus==0.5.7', 'console_scripts', 'spyking-circus')()
  File "/Users/benacland/anaconda/envs/spykpi/lib/python3.5/site-packages/circus/scripts/launch.py", line 384, in main
    mygui = gui.PreviewGUI(params, show_fit=True)
  File "/Users/benacland/anaconda/envs/spykpi/lib/python3.5/site-packages/circus/shared/gui.py", line 1101, in __init__
    self.get_data()
  File "/Users/benacland/anaconda/envs/spykpi/lib/python3.5/site-packages/circus/shared/gui.py", line 1179, in get_data
    self.data       = self.data_file.get_snippet(t_start, self.chunk_size, nodes=self.nodes)
  File "/Users/benacland/anaconda/envs/spykpi/lib/python3.5/site-packages/circus/files/datafile.py", line 449, in get_snippet
    return self.get_data(0, chunk_size=length, padding=(local_time, local_time), nodes=nodes)[0]
  File "/Users/benacland/anaconda/envs/spykpi/lib/python3.5/site-packages/circus/files/datafile.py", line 459, in get_data
    return self.read_chunk(idx, chunk_size, padding, nodes), self.t_start + idx*chunk_size      
  File "/Users/benacland/anaconda/envs/spykpi/lib/python3.5/site-packages/circus/files/openephys.py", line 113, in read_chunk
    local_chunk[:, count] = self.data[i][data_slice]
  File "/Users/benacland/anaconda/envs/spykpi/lib/python3.5/site-packages/numpy/core/memmap.py", line 335, in __getitem__
    res = super(memmap, self).__getitem__(index)
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

... submitting PR shortly.

**Comment by beOn** [comment]
Hopefully this atones somewhat for the bogus issue earlier today :/

**Comment by yger** [comment]
Indeed, thanks for the PR, this could lead to errors with Python3.5. However, I'm not sure this is the problem for the bug you saw before. Because such a get_snippet function is not called when loading the phy GUI. But it could be something similar maybe

**Comment by beOn** [comment]
Ah, what I meant was, I took up some of your time somewhat needlessly over the other issue, so hope this little fix repays some karmic debt.

**Comment by yger** [comment]
No worries, thanks a lot for your help in troubleshooting!

Le ven. 7 juil. 2017 à 17:07, Ben Acland <notifications@github.com> a
écrit :
