### ISSUE TITLE
error with fitting.py

### ISSUE THREAD

**Issue by paul-aparicio** [spyking-circus/spyking-circus#399]
Hello! I am having a problem with spyking circus throwing an error during the fitting. It displays an error message, then keeps on going, but then it hangs and runs the CPUs at 100%, but never completes the task, Any help would be greatly appreciated. I am running spyking circus 1.1.0 through spikeinterface (v0.13) and have the following installed in the environment:

numpy 1.20.3
scipy 1.7.3
 
The error I get during runtime is:

Here comes the SpyKING CIRCUS using 26 CPUs and 16 templates...

  0%|                                            |[00:00<?, ?it/s]

  2%|▋                                  |[00:00<00:04, 512.15it/s]

  4%|█▍                                 |[00:00<00:07, 307.89it/s]

  6%|█▉                                 |[00:00<00:08, 281.11it/s]

  7%|██▎                                |[00:00<00:08, 267.25it/s]

  8%|██▊                                |[00:00<00:08, 265.80it/s]

  9%|███▏                               |[00:00<00:08, 258.66it/s]

 10%|███▌                               |[00:00<00:08, 257.06it/s]

 11%|███▊                               |[00:01<00:09, 241.72it/s]

 12%|████▏                              |[00:01<00:09, 238.73it/s]

 13%|████▌                              |[00:01<00:09, 240.61it/s]

 14%|████▉                              |[00:01<00:09, 237.94it/s]

 15%|█████▏                             |[00:01<00:08, 240.68it/s]

 16%|█████▌                             |[00:01<00:08, 239.89it/s]

 17%|█████▉                             |[00:01<00:08, 251.42it/s]

 18%|██████▎                            |[00:01<00:08, 256.55it/s]

 19%|██████▋                            |[00:01<00:08, 255.90it/s]

 20%|███████                            |[00:01<00:08, 248.08it/s]

 21%|███████▍                           |[00:02<00:08, 245.68it/s]

 22%|███████▋                           |[00:02<00:08, 240.14it/s]

 23%|████████                           |[00:02<00:07, 245.94it/s]

 24%|████████▍                          |[00:02<00:07, 241.43it/s]

 25%|████████▊                          |[00:02<00:07, 241.81it/s]

 27%|█████████▌                         |[00:02<00:05, 335.53it/s]

 29%|██████████▎                        |[00:02<00:04, 389.64it/s]

 31%|███████████                        |[00:02<00:04, 420.95it/s]

 33%|███████████▋                       |[00:02<00:03, 449.75it/s]

 36%|████████████▌                      |[00:03<00:03, 493.01it/s]

 38%|█████████████▎                     |[00:03<00:03, 514.16it/s]

 40%|██████████████▏                    |[00:03<00:02, 532.67it/s]

 43%|██████████████▉                    |[00:03<00:02, 555.57it/s]

 45%|███████████████▊                   |[00:03<00:02, 562.09it/s]

 47%|████████████████▌                  |[00:03<00:02, 565.18it/s]

 50%|█████████████████▎                 |[00:03<00:02, 450.81it/s]

 52%|██████████████████                 |[00:03<00:02, 467.55it/s]

 54%|██████████████████▊                |[00:03<00:02, 494.17it/s]

 56%|███████████████████▋               |[00:04<00:02, 531.26it/s]

Traceback (most recent call last):

  File "/home/paul/anaconda3/envs/spikes/bin/spyking-circus-subtask", line 8, in <module>

    sys.exit(main())

  File "/home/paul/anaconda3/envs/spikes/lib/python3.7/site-packages/circus/scripts/subtask.py", line 54, in main

    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)

  File "/home/paul/anaconda3/envs/spikes/lib/python3.7/site-packages/circus/__init__.py", line 23, in launch

    module.main(params, nb_cpu, nb_gpu, use_gpu)

  File "/home/paul/anaconda3/envs/spikes/lib/python3.7/site-packages/circus/fitting.py", line 591, in main

    tmp1 += c_overs[best_template2_index].multiply(-best_amp2)

  File "/home/paul/anaconda3/envs/spikes/lib/python3.7/site-packages/scipy/sparse/base.py", line 415, in __add__

    return self._add_sparse(other)

  File "/home/paul/anaconda3/envs/spikes/lib/python3.7/site-packages/scipy/sparse/compressed.py", line 360, in _add_sparse

    return self._binopt(other, '_plus_')

  File "/home/paul/anaconda3/envs/spikes/lib/python3.7/site-packages/scipy/sparse/compressed.py", line 1255, in _binopt

    A = self.__class__((data, indices, indptr), shape=self.shape)

  File "/home/paul/anaconda3/envs/spikes/lib/python3.7/site-packages/scipy/sparse/compressed.py", line 106, in __init__

    self.check_format(full_check=False)

  File "/home/paul/anaconda3/envs/spikes/lib/python3.7/site-packages/scipy/sparse/compressed.py", line 160, in check_format

    self.data = to_native(self.data)

  File "/home/paul/anaconda3/envs/spikes/lib/python3.7/site-packages/scipy/sparse/sputils.py", line 92, in to_native

    return np.asarray(A, dtype=A.dtype.newbyteorder('native'))

  File "/home/paul/anaconda3/envs/spikes/lib/python3.7/site-packages/numpy/core/_asarray.py", line 100, in asarray

    return _asarray_with_like(a, dtype=dtype, order=order, like=like)

  File "<__array_function__ internals>", line 6, in asarray

TypeError: The `like` argument must be an array-like that implements the `__array_function__` protocol.

 59%|████████████████████▌              |[00:04<00:02, 431.46it/s]

 60%|█████████████████████▏             |[00:04<00:02, 408.34it/s]

 63%|█████████████████████▉             |[00:04<00:02, 442.31it/s]

 65%|██████████████████████▊            |[00:04<00:01, 491.27it/s]

 68%|███████████████████████▊           |[00:04<00:01, 548.73it/s]

 70%|████████████████████████▋          |[00:04<00:01, 565.37it/s]

 73%|█████████████████████████▌         |[00:04<00:01, 605.34it/s]

 76%|██████████████████████████▍        |[00:04<00:01, 612.49it/s]

 78%|███████████████████████████▍       |[00:05<00:00, 640.54it/s]

 81%|████████████████████████████▍      |[00:05<00:00, 646.46it/s]

 84%|█████████████████████████████▎     |[00:05<00:00, 659.00it/s]

 86%|██████████████████████████████▎    |[00:05<00:00, 659.45it/s]

 90%|███████████████████████████████▎   |[00:05<00:00, 695.88it/s]

 92%|████████████████████████████████▎  |[00:05<00:00, 678.85it/s]

 95%|█████████████████████████████████▎ |[00:05<00:00, 674.28it/s]

 98%|██████████████████████████████████▏|[00:05<00:00, 673.76it/s]

100%|███████████████████████████████████|[00:05<00:00, 433.58it/s]

The program just hangs here (left it running for a hours, but no change). Thanks again for any help.

**Comment by yger** [comment]
I'm never encountered such an error, not sure I an reproduce that. What is your python version ? 

I want to highlight that SC has now moved within the context of spikeinterface, with a completly rewritten engine (spyking-circus 2). Publication is on the way, but the software should be more flexible, faster, better, and easier to integrate with analysis pipelines. See https://github.com/SpikeInterface/spikeinterface and do not hesitate if questions
