### ISSUE TITLE
Cannot run spyking-circus on openephys files

### ISSUE THREAD

**Issue by galenlynch** [spyking-circus/spyking-circus#47]
When I try to run spyking-circus on my openephys data files, I get the following error:

```
$ spyking-circus Continuous_Data.openephys -c 8 -H ~/Documents/Code/spyking-circus/circus.host
----------------------------  Error  -----------------------------
| There is an error in the _read_from_header method of the wrapper
'encoding' is an invalid keyword argument for this function
------------------------------------------------------------------
----------------------------  Error  -----------------------------
| Shape of the data is not defined. Are you sure of the wrapper?
------------------------------------------------------------------
```

There is no information in the log file about this error.

The top of my params file is:
```
[data]
file_format    = openephys             # Can be raw_binary, openephys, hdf5, ... See >> spyking-circus help -i for more info
stream_mode    = multi-files                  # None by default. Can be multi-files, or anything depending to the file format
```

Is there an error in how I'm calling spyking-circus?

**Comment by yger** [comment]
So far, from what I can tell, you're using it right, and it should work.
What is your python version/os, and your spyking-circus version? Are you
using the latest 0.6.1?

Best

Pierre

Le ven. 27 oct. 2017 à 19:04, Galen Lynch <notifications@github.com> a
écrit :

**Comment by galenlynch** [comment]
```
$ lsb_release -a                                                                                                                                            ⏎
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

$ python -V
Python 3.6.3 :: Anaconda, Inc.

$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
```

**Comment by galenlynch** [comment]
I switched to 0.6.1, but I don't know if the I installed spyking correctly:

```
$ nosetests tests/
E
======================================================================
ERROR: Failure: SyntaxError (Missing parentheses in call to 'print'. Did you mean print(print "To generate synthetic datasets, you must provide output and type")? (__init__.py, line 63))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/galen/anaconda3/envs/spyking/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/galen/anaconda3/envs/spyking/lib/python3.6/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/galen/anaconda3/envs/spyking/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/galen/anaconda3/envs/spyking/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/galen/anaconda3/envs/spyking/lib/python3.6/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/home/galen/anaconda3/envs/spyking/lib/python3.6/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/galen/Documents/Code/spyking-circus/tests/__init__.py", line 63
    print "To generate synthetic datasets, you must provide output and type"
                                                                           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "To generate synthetic datasets, you must provide output and type")?

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

**Comment by yger** [comment]
Ok, my bad, there was indeed a bug for OpenEphys file and python3, I just
pushed a fix. Please install latest version from git (tagged 0.6.2) and you
should be able to get openephys file working. The test suite is not
updated, no worries, this is on the todolist...

Best

Pierre

2017-10-27 20:47 GMT+02:00 Galen Lynch <notifications@github.com>:

**Comment by galenlynch** [comment]
Thanks for attending to this so quickly! I just converted my files to a flat binary and am running spyking-circus on that, but after it's complete I"ll try the new code and get back to you.
