### ISSUE TITLE
openmpi 3.0.0 not working 

### ISSUE THREAD

**Issue by yger** [spyking-circus/spyking-circus#93]
There is a problem with MPI 3.0 and the code, because of recursive calls to mpiexec. Need to be fixed or to pin version

**Comment by yger** [comment]
Currently, the quick solution is to switch and recommend MPICH instead, bundled with conda

**Comment by mattgaidica** [comment]
@yger would this be causing the error: `Step "filtering" failed for reason Command '['mpirun', '-x', 'PATH', '-np', '4', 'spyking-circus-subtask', 'filtering', '/Users/mattgaidica/Documents/Data/SpyKING CIRCUS/20160426_patch3/patch_3/patch_3/tmp/preview.dat', '4', '0', 'False']' returned non-zero exit status 1!`? 

I also found that the ground truth data probe file needs to be modified for Python 3: `channel_groups[1]["channels"] = list(range(126)) + list(range(128,254))` (I didn't see this noted anywhere) Thanks.

**Comment by yger** [comment]
Yes. Sadly, for now, you need to switch to mpich

Le sam. 22 déc. 2018 à 18:30, Matt Gaidica <notifications@github.com> a
écrit :

**Comment by mattgaidica** [comment]
How do you accomplish that?

**Comment by yger** [comment]
Using conda this is the default. But otherwise this depends on your OS.
Using Ubuntu, you need to to
>> sudo apt remove openmpi-bin
>> sudo apt install mpich libmpich-dev (or something like that

Then you may have to uninstall mpi4py and reinstall it


Le sam. 22 déc. 2018 à 19:47, Matt Gaidica <notifications@github.com> a
écrit :

**Comment by jschmiedt** [comment]
I ran into the same problem even though I installed Spyking Cirucs via conda (v4.5.12):
```conda install -c conda-forge -c spyking-circus spyking-circus```
Removing `openmpi` and manually installing`mpich` via 
```conda install -c conda-forge mpich```
before `spyking-circus` fixed the problem. Note that `mpich` doesn't support the `max-slots` option in the hosts file.

**Comment by yger** [comment]
thanks for the comment. Indeed, max-slots is not valid with mpich, one should rather use a syntax like
IP:nb_cores

**Comment by jschmiedt** [comment]
Do you have an idea when this problem with OpenMPI will be fixed? 

We'd like to use SpykingCircus with our SLURM scheduler, which plays nicely with OpenMPI, not so much with MPICH. Do you have any experience with job schedulers?

**Comment by yger** [comment]
I don't have much experience with job schedulers, sadly. I'm still trying to properly figure out/patch the OpenMPI problem, related to the implementation of the MPI API, but I guess it will take a good couple of days. But I'm on it

**Comment by jschmiedt** [comment]
Thanks for the info, and no rush. For our current channel counts (<128) the 16 cores of each individual machine is plenty.
Once the bug is fixed, I'm happy to share our experiences using OpenMPI, SLURM and SpykingCircus.

**Comment by jschmiedt** [comment]
Using `mpich`  I now get an error during clustering:
```
Merging similar templates...
Traceback (most recent call last):
  File "/opt/ESIsoftware/python/envs/spikesorting/bin/spyking-circus-subtask", line 11, in <module>
    load_entry_point('spyking-circus==0.7.5', 'console_scripts', 'spyking-circus-subtask')()
  File "/opt/ESIsoftware/python/envs/spikesorting/lib/python3.5/site-packages/circus/scripts/subtask.py", line 43, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "/opt/ESIsoftware/python/envs/spikesorting/lib/python3.5/site-packages/circus/__init__.py", line 21, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "/opt/ESIsoftware/python/envs/spikesorting/lib/python3.5/site-packages/circus/clustering.py", line 1060, in main
    merged1 = algo.merging_cc(params, nb_cpu=nb_cpu, nb_gpu=nb_gpu, use_gpu=use_gpu)
  File "/opt/ESIsoftware/python/envs/spikesorting/lib/python3.5/site-packages/circus/shared/algorithms.py", line 403, in merging_cc
    overlap  = get_overlaps(params, extension='-merging', erase=True, normalize=True, maxoverlap=False, verbose=False, half=True, use_gpu=use_gpu, nb_cpu=nb_cpu, nb_gpu=nb_gpu)
  File "/opt/ESIsoftware/python/envs/spikesorting/lib/python3.5/site-packages/circus/shared/files.py", line 1403, in get_overlaps
    templates  = load_data_memshared(params, 'templates', normalize=normalize)
  File "/opt/ESIsoftware/python/envs/spikesorting/lib/python3.5/site-packages/circus/shared/files.py", line 389, in load_data_memshared
    sub_comm, is_local = get_local_ring(local_only)
  File "/opt/ESIsoftware/python/envs/spikesorting/lib/python3.5/site-packages/circus/shared/mpi.py", line 31, in get_local_ring
    sub_comm  = comm.Split_type(MPI.COMM_TYPE_SHARED, myip)
  File "MPI/Comm.pyx", line 214, in mpi4py.MPI.Comm.Split_type (src/mpi4py.MPI.c:92130)
NotImplementedError
----------------------------  Error  -----------------------------
| Step "clustering" failed for reason Command '['mpiexec', '-f', '/home/schmiedtj_it/spyking-circus/circus.hosts', '-np', '1', 'spyking-circus-subtask', 'clustering', '/mnt/hpx/slurm/schmiedtj_it/spikesorting/data/MT_RFmapping_session-168a1_Raws_Ch1.sev', '1', '0', 'False']' returned non-zero exit status 1!
------------------------------------------------------------------
```
Do you have an idead what could be the reason?

**Comment by yger** [comment]
Not really. What is the mpich version used ? This MPI library is really
full of surprise

Best

Pierre

Le mar. 8 janv. 2019 à 14:16, Joscha Schmiedt <notifications@github.com> a
écrit :

**Comment by yger** [comment]
Ok, and if you are a bit experienced with coding, can you edit L31 in /opt/ESIsoftware/python/envs/spikesorting/lib/python3.5/site-packages/circus/shared/mpi.py, where the error is, and tell me if changing the line from


sub_comm = comm.Split(myip, 0)

changes the error (it should trigger a similar one, but maybe somewhere else). If so, we could patch using this syntax, but strangly, here with ubuntu, everything works fine

**Comment by ivan-pi** [comment]
I have succesfully used the explicit list of packages provided by @jschmiedt  to create an environment and get spyking-circus run on a linux cluster using:  `conda create --name spyking --file openmpi_workaround.text`, and afterwards installing spyking-circus in the environment: `pip install spyking-circus`.

@jschmiedt I would also like to use SLURM to submit a spike sorting job but have little experience in writing SLURM batch scripts. I managed to get it run on a single node by using `salloc --ntasks=32` and then passing spyking-circus a hostfile containing only the relative host name "+n1" and the same number of cores in spyking-circus. Would you be able to provide a minimal SLURM batch script and hostfile example for using spyking-circus with a job scheduler?

**Comment by jwouters91** [comment]
Both links related to the mpi packages in the openmpi_workaround.txt are dead. I succeed in installing a working copy of spyking-circus by creating a conda environment from the explicit list of packages where I commented out the two mpi-related packages.

Then I compiled openmpi (version 1.10.2 as suggested by the list) from source by following the instructions on the following webpage: http://butka.me/linux/how-to-install-openmpi-on-ubuntu-14-04/ (note that I'm running ubuntu 16.04).

Next, I installed the suggested version of mpi4py through pip: ``` pip install mpi4py==2.0.0 ```. Finally, I installed spyking circus using pip as shown in the previous post by @ivan-pi.

**Comment by pplenck** [comment]
Guys, any news?
after I gave up on running spyking-circus on my windows/dell (issue with PyQt5 unresolved),
I tried to do the same with my mac: I can't even get to the preview:

filtering" failed for reason Command '['mpirun', '-x', 'PATH', '-np', '2', 'spyking-circus-subtask'...

I tried conda install mpi4py... channel is dead
so I used conda-forge and it worked but the issue is still there.
can anyone help me I don't know how to compile and what jwousters91 did, it is very far from my ballpark. also how do you `Removing openmpi and manually installingmpich' on anaconda navigator, manually?
-I've been trying to get this to work for 5 days now. I am getting pretty depressed.

**Comment by yger** [comment]
Sorry to hear that you are facing so many problems. Yesterday, I made a fresh install on Win10 with anaconda 3 and everything worked fine, out of the box. So I'm still not sure of what is the problem with PyQt4/5. Please understand that despite the fact that we are doing our best to maintain the software (and will continue in the future), cross platform installs are not my cup of tea...

Otherwise, on your mac, your problem is clearly because you are using openmpi v3 ( started working on a fix, but no time yet to finish it). I guess you can try to force the openmpi version in conda:

conda install openmpi=2.0.0
conda install mpi4py=2.0.0

These commands are not tested, I'll do that later today and come back to you.

**Comment by crnolan** [comment]
@yger, I've run into this issue and tried the workaround you suggested (modifying the comm.Split_type to comm.Split), and now the exception has become:

```
Traceback (most recent call last):
  File "/home/ss/anaconda3/envs/spyking-circus/bin/spyking-circus-subtask", line 11, in <module>
    load_entry_point('spyking-circus', 'console_scripts', 'spyking-circus-subtask')()
  File "/home/ss/Development/spyking-circus/build/lib/circus/scripts/subtask.py", line 43, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "/home/ss/Development/spyking-circus/build/lib/circus/__init__.py", line 21, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "/home/ss/Development/spyking-circus/build/lib/circus/clustering.py", line 1072, in main
    merged1 = algo.merging_cc(params, nb_cpu=nb_cpu, nb_gpu=nb_gpu, use_gpu=use_gpu)
  File "/home/ss/Development/spyking-circus/build/lib/circus/shared/algorithms.py", line 530, in merging_cc
    overlap  = get_overlaps(params, extension='-merging', erase=True, normalize=True, maxoverlap=False, verbose=False, half=True, use_gpu=use_gpu, nb_cpu=nb_cpu, nb_gpu=nb_gpu)
  File "/home/ss/Development/spyking-circus/build/lib/circus/shared/files.py", line 1495, in get_overlaps
    templates  = load_data_memshared(params, 'templates', normalize=normalize)
  File "/home/ss/Development/spyking-circus/build/lib/circus/shared/files.py", line 421, in load_data_memshared
    win_data    = MPI.Win.Allocate_shared(data_bytes, floatsize, comm=sub_comm)
  File "MPI/Win.pyx", line 106, in mpi4py.MPI.Win.Allocate_shared (src/mpi4py.MPI.c:125279)
NotImplementedError
```
I'm using mpich2 and python 3.6 (on a single desktop machine). Any thoughts?

**Comment by yger** [comment]
Are you using the last version of the software (0.8.0) installed from git,
and/or can you provide me the log file of your run

Le jeu. 6 juin 2019 à 03:24, Christopher Nolan <notifications@github.com> a
écrit :

**Comment by crnolan** [comment]
I'm running from an up-to-date git master repository. I'm using anaconda on Ubuntu, my environment was set up using:

```
conda create -n spyking-circus python=3.6 cython colorama h5py hdf5 libgcc matplotlib mpi4py numpy psutil python-blosc scikit-learn scipy setuptools tqdm statsmodels
source activate spyking-circus
conda install -c conda-forge pyqt=4.11.4=py36_3 
```
Then I install the git version from the repository folder using:
```
pip install -e .
```
I've attached the log file (with paths shortened) of the unedited version (i.e. with the original error on the Split_type). I can attach another if required after I try the edit again, but I didn't notice any differences in the log file.
[Bucket_test_2.log](https://github.com/spyking-circus/spyking-circus/files/3264045/Bucket_test_2.log)

**Comment by yger** [comment]
When you launch the code, you have the option shared memory set to True I guess, on the main display, am I right? And if you go into a python console and enter

```
from mpi4py import MPI
SHARED_MEMORY = (hasattr(MPI.Win, 'Allocate_shared') and callable(getattr(MPI.Win, 'Allocate_shared')))
```
What is the value of SHARED_MEMORY ? True ?

**Comment by crnolan** [comment]
That's right, SHARED_MEMORY in that situation ==True.

**Comment by JoseGuzman** [comment]
Hi, 

I am facing exactly the same situation. I have **spyking-circus 0.8** from the [master](https://github.com/spyking-circus/spyking-circus) repository in a conda environment with Ubutu 18.04 with the following packages and versions:
```bash
mpi                       1.0                       mpich
mpi4py                    2.0.0                    py36_2
mpich                     3.2.1                hf39692e_8
mpich2                    1.4.1p1                       0
```

like @crnolan , `SHARED_MEMORY == True` in mpi4py. I guess, I am using MPICH and not OpenMPI in that environment. I attach here the versions of both libraries that I have in my system.
```bash 
OpenMPI: 2.1.1
MPICH: 3.2.1
```

When I run `spyking-circus myrecording.dat -c1` I get the following error in the clustering (even with one core only!).
```python
Traceback (most recent call last):
  File "/home/segundo.martinez/miniconda3/envs/spyking-circus/bin/spyking-circus-subtask", line 11, in <module>
    load_entry_point('spyking-circus', 'console_scripts', 'spyking-circus-subtask')()
  File "/home/segundo.martinez/git/spyking-circus/build/lib/circus/scripts/subtask.py", line 43, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "/home/segundo.martinez/git/spyking-circus/build/lib/circus/__init__.py", line 21, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "/home/segundo.martinez/git/spyking-circus/build/lib/circus/clustering.py", line 1072, in main
    merged1 = algo.merging_cc(params, nb_cpu=nb_cpu, nb_gpu=nb_gpu, use_gpu=use_gpu)
  File "/home/segundo.martinez/git/spyking-circus/build/lib/circus/shared/algorithms.py", line 530, in merging_cc
    overlap  = get_overlaps(params, extension='-merging', erase=True, normalize=True, maxoverlap=False, verbose=False, half=True, use_gpu=use_gpu, nb_cpu=nb_cpu, nb_gpu=nb_gpu)
  File "/home/segundo.martinez/git/spyking-circus/build/lib/circus/shared/files.py", line 1495, in get_overlaps
    templates  = load_data_memshared(params, 'templates', normalize=normalize)
  File "/home/segundo.martinez/git/spyking-circus/build/lib/circus/shared/files.py", line 389, in load_data_memshared
    sub_comm, is_local = get_local_ring(local_only)
  File "/home/segundo.martinez/git/spyking-circus/build/lib/circus/shared/mpi.py", line 32, in get_local_ring
    sub_comm  = comm.Split_type(MPI.COMM_TYPE_SHARED, myip)
  File "MPI/Comm.pyx", line 214, in mpi4py.MPI.Comm.Split_type (src/mpi4py.MPI.c:92130)
NotImplementedError
```

Then, I edited L43the file /git/spiking-circus/circus/shared/mpi.py suggested by @yger 
```python
31     else:
32         sub_comm = comm.Split(myip, 0)
33         #sub_comm  = comm.Split_type(MPI.COMM_TYPE_SHARED, myip) 
```

and after `pip3 install -e .`, when I run the program again, I returns an error in /shared/files.py.
```python
 Traceback (most recent call last):
  File "/home/segundo.martinez/miniconda3/envs/spyking-circus/bin/spyking-circus-subtask", line 11, in <module>
    load_entry_point('spyking-circus', 'console_scripts', 'spyking-circus-subtask')()
  File "/home/segundo.martinez/git/spyking-circus/build/lib/circus/scripts/subtask.py", line 43, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "/home/segundo.martinez/git/spyking-circus/build/lib/circus/__init__.py", line 21, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "/home/segundo.martinez/git/spyking-circus/build/lib/circus/clustering.py", line 1072, in main
    merged1 = algo.merging_cc(params, nb_cpu=nb_cpu, nb_gpu=nb_gpu, use_gpu=use_gpu)
  File "/home/segundo.martinez/git/spyking-circus/build/lib/circus/shared/algorithms.py", line 530, in merging_cc
    overlap  = get_overlaps(params, extension='-merging', erase=True, normalize=True, maxoverlap=False, verbose=False, half=True, use_gpu=use_gpu, nb_cpu=nb_cpu, nb_gpu=nb_gpu)
  File "/home/segundo.martinez/git/spyking-circus/build/lib/circus/shared/files.py", line 1495, in get_overlaps
    templates  = load_data_memshared(params, 'templates', normalize=normalize)
  File "/home/segundo.martinez/git/spyking-circus/build/lib/circus/shared/files.py", line 421, in load_data_memshared
    win_data    = MPI.Win.Allocate_shared(data_bytes, floatsize, comm=sub_comm)
  File "MPI/Win.pyx", line 106, in mpi4py.MPI.Win.Allocate_shared (src/mpi4py.MPI.c:125279)
NotImplementedError
```

I guess, L412 in /shared/files.py has to be changed.

```python
 417             if local_rank == 0:
 418                 indices_bytes = short_size * intsize
 419                 data_bytes    = long_size * floatsize
 420 
 421             win_data    = MPI.Win.Allocate_shared(data_bytes, floatsize, comm=sub_comm)                                                                    
 422             win_indices = MPI.Win.Allocate_shared(indices_bytes + indptr_bytes, intsize, comm=sub_comm)

```

**Comment by crnolan** [comment]
Turns out mpich==3.2.1 seems to work with the clean repository version; set up an environment with:
```
conda create -n spyking-circus python=3.6 cython colorama h5py hdf5 libgcc matplotlib mpi4py numpy psutil python-blosc scikit-learn scipy setuptools tqdm
source activate spyking-circus
conda install -c conda-forge pyqt=4.11.4=py36_3
conda install -c conda-forge mpi4py=3.0.0=py36_mpich_3
conda install -c spyking-circus spyking-circus
```

**Comment by yger** [comment]
Ok, good to know. I'll still try to debug why this is not working with
mpich2, as I think it should. And as soon as I'll find time, I'll make
everything compatible with openmpi3, default on Ubuntu. On my todo list...

**Comment by JoseGuzman** [comment]
Thank you very much @yger ,  @crnolan , it worked like a charm!

**Comment by JoseGuzman** [comment]
If I want to use [phy](https://github.com/cortex-lab/phy), I understand that all what I'd have to do is:
```bash
$ git clone https://github.com/cortex-lab/phy
$ cd phy
$ conda activate spyking-circus
$ pip install . -e
```

**Comment by yger** [comment]
Actually, you should rather do

$ conda activate spyking-circus

$ git clone https://github.com/cortex-lab/phy$ cd phy
$ git checkout dev

$ pip install . -e

$ git clone https://github.com/cortex-lab/phylab$ cd phylab
$ pip install . -e

You need both phy 2.0 and phylib for the latest version of SC (0.8.0). Docs
will be updated accordingly

Best

Pierre

Le mer. 12 juin 2019 à 12:20, Jose Guzman <notifications@github.com> a
écrit :

**Comment by JoseGuzman** [comment]
Fantastic! I could help with the documentation!

**Comment by JoseGuzman** [comment]
Are you sure we need to force PyQt4? After converting to Phy format, an error suggest to install PyQt5.
 
```python
Traceback (most recent call last):
  File "/home/segundo.martinez/miniconda3/envs/sorting/bin/circus-gui-python", line 11, in <module>
    load_entry_point('spyking-circus', 'console_scripts', 'circus-gui-python')()
  File "/home/segundo.martinez/miniconda3/envs/sorting/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/segundo.martinez/miniconda3/envs/sorting/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/home/segundo.martinez/miniconda3/envs/sorting/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/home/segundo.martinez/miniconda3/envs/sorting/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/segundo.martinez/git/spyking-circus/build/lib/circus/scripts/python_gui.py", line 33, in <module>
    from phy.gui import create_app, run_app
  File "/home/segundo.martinez/git/phy/phy/gui/__init__.py", line 6, in <module>
    from .qt import require_qt, create_app, run_app
  File "/home/segundo.martinez/git/phy/phy/gui/qt.py", line 30, in <module>
    from PyQt5.QtCore import (Qt, QByteArray, QMetaObject, QObject,  # noqa
ModuleNotFoundError: No module named 'PyQt5'
```

**Comment by yger** [comment]
Ah yes, you are right. Phy 1.xx was.not compatible with PyQt5, but now phy
2.0 is. I should update the requirements before the release of
Spyking-circus 0.8.0 that will happen soon. Since the software is
compatible with both must versions, now I'll push for PyQt5

Best

Pierre

Le mer. 12 juin 2019 à 16:43, Jose Guzman <notifications@github.com> a
écrit :

**Comment by JoseGuzman** [comment]
Thanks @yger . Then, I will copy below the instructions to install spyking-circus with ``` mpich==3.2.1```. Note **pyopengl** , **colorcet**, **click**,  and **vispy** were added, as I was asked to install them. 

```bash
$ conda create -n spyking-circus python=3.6
$ conda activate spyking-circus # use source activate spyking-circus in Windows
$ conda install  cython colorama h5py hdf5 libgcc matplotlib mpi4py numpy psutil python-blosc scikit-learn scipy setuptools tqdm pyopengl pyqt colorcet click
$ conda install -c conda-forge mpi4py=3.0.0=py36_mpich_3 # key step!
$ conda install -c spyking-circus spyking-circus
```

**Comment by mhhennig** [comment]
Just checking if anyone has had a problem with SC not terminating its threads. The install guide by @JoseGuzman above works fine. SC starts up, and get to the point where it says: `A basis with 5 dimensions has been built`. Then the main process, and all threads, are just at 0% cpu load forever, and not terminated.
pstree:
```
        ├─screen───bash───ZMQbg/1─┬─ZMQbg/1─┬─python
        │                         │         ├─spyking-circus─┬─mpiexec───hydra_pmi_proxy───24*[spyking-circus-]
        │                         │         │                └─python
        │                         │         └─19*[{ZMQbg/1}]
```
Note this is run from a jupyter notebook, hence the extra `ZMQ...`

**Comment by JoseGuzman** [comment]
Hi Mattias!

Did you try to use a new and dedicated conda environment and use Spyking-circus from the command terminal?  It worked for me when following the instructions in https://github.com/spyking-circus/spyking-circus/issues/93#issuecomment-501318329

**Comment by mhhennig** [comment]
Aha, running in a notebook is the problem. As a standalone script it works. Thanks @JoseGuzman!
